var h;h||=typeof Module != 'undefined' ? Module : {};var ba="object"==typeof window,ca="function"==typeof importScripts,da="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node;h.sf||(h.sf=0);h.sf++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||function(b){function c(p,r,t,A){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(p,function(v,u){v?A(v):t(u.buffer)});else{var x=new XMLHttpRequest;x.open("GET",p,!0);x.responseType="arraybuffer";x.onprogress=function(v){var u=r;v.total&&(u=v.total);if(v.loaded){x.pe?
h.Ue[p].loaded=v.loaded:(x.pe=!0,h.Ue||(h.Ue={}),h.Ue[p]={loaded:v.loaded,total:u});var H=u=v=0,O;for(O in h.Ue){var aa=h.Ue[O];v+=aa.total;u+=aa.loaded;H++}v=Math.ceil(v*h.sf/H);h.setStatus?.(`Downloading data... (${u}/${v})`)}else h.Ue||h.setStatus?.("Downloading data...")};x.onerror=function(){throw Error("NetworkError for: "+p);};x.onload=function(){if(200==x.status||304==x.status||206==x.status||0==x.status&&x.response)t(x.response);else throw Error(x.statusText+" : "+x.responseURL);};x.send(null)}}
function d(p){console.error("package error:",p)}function e(p){function r(v,u,H){this.start=v;this.end=u;this.audio=H}function t(v){if(!v)throw"Loading data file failed."+Error().stack;if(v.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);r.prototype.Se=v;v=b.files;for(var u=0;u<v.length;++u)r.prototype.pe[v[u].filename].onload();p.removeRunDependency("datafile_drom.data")}r.prototype={pe:{},open:function(v,u){this.name=u;this.pe[u]=this;
p.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.finish(this.Se.subarray(this.start,this.end))},finish:function(v){p.FS_createDataFile(this.name,null,v,!0,!0,!0);p.removeRunDependency(`fp ${this.name}`);this.pe[this.name]=null}};for(var A=b.files,x=0;x<A.length;++x)(new r(A[x].start,A[x].end,A[x].audio||0)).open("GET",A[x].filename);p.addRunDependency("datafile_drom.data");p.Sf||(p.Sf={});p.Sf["drom.data"]={Eg:!1};n?(t(n),n=null):l=t}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,ea("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=h.locateFile?h.locateFile("drom.data",
""):"drom.data",g=b.remote_package_size,l=null,n=h.getPreloadedPackage?h.getPreloadedPackage(f,g):null;n||c(f,g,function(p){l?(l(p),l=null):n=p},d);h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))}({files:[{filename:"/drom.pd",start:0,end:86504}],remote_package_size:86504})})();var fa=Object.assign({},h),ha=[],ia="./this.program",ja=(a,b)=>{throw b;},ka="",la,ma;
if(da){var fs=require("fs"),na=require("path");ka=__dirname+"/";ma=a=>{a=oa(a)?new URL(a):na.normalize(a);return fs.readFileSync(a)};la=a=>{a=oa(a)?new URL(a):na.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!h.thisProgram&&1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/"));ha=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof pa||a.context instanceof pa))throw a;
});ja=(a,b)=>{process.exitCode=a;throw b;}}else if(ba||ca)ca?ka=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=ka.startsWith("blob:")?"":ka.substr(0,ka.replace(/[?#].*/,"").lastIndexOf("/")+1),ca&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=a=>oa(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=
()=>{(200==d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var qa=h.print||console.log.bind(console),ea=h.printErr||console.error.bind(console);Object.assign(h,fa);fa=null;h.arguments&&(ha=h.arguments);h.thisProgram&&(ia=h.thisProgram);h.quit&&(ja=h.quit);var ra;h.wasmBinary&&(ra=h.wasmBinary);
var sa,ta=!1,ua,k,m,va,wa,q,w,y,z,xa=[],ya=[],za=[],Aa=[];function Ba(){var a=h.preRun.shift();xa.unshift(a)}var Ca=0,Da=null,Ea=null;function Fa(){Ca++;h.monitorRunDependencies?.(Ca)}function Ga(){Ca--;h.monitorRunDependencies?.(Ca);if(0==Ca&&(null!==Da&&(clearInterval(Da),Da=null),Ea)){var a=Ea;Ea=null;a()}}function Ha(a){h.onAbort?.(a);a="Aborted("+a+")";ea(a);ta=!0;ua=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
var Ia=a=>a.startsWith("data:application/octet-stream;base64,"),oa=a=>a.startsWith("file://"),Ja;function Ka(a){if(a==Ja&&ra)return new Uint8Array(ra);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}function La(a){return ra?Promise.resolve().then(()=>Ka(a)):la(a).then(b=>new Uint8Array(b),()=>Ka(a))}function Ma(a,b,c){return La(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{ea(`failed to asynchronously prepare wasm: ${d}`);Ha(d)})}
function Na(a,b){var c=Ja;ra||"function"!=typeof WebAssembly.instantiateStreaming||Ia(c)||oa(c)||da||"function"!=typeof fetch?Ma(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){ea(`wasm streaming compile failed: ${e}`);ea("falling back to ArrayBuffer instantiation");return Ma(c,a,b)}))}
var B,C,Ra={136173:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,136320:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,136554:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.se||("undefined"!==typeof AudioContext?b.se=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.se=new webkitAudioContext),b.se&&
Oa(b.se));return void 0===b.se?-1:0},137047:()=>h.SDL2.se.sampleRate,137115:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.cf&&(clearTimeout(g.capture.cf),g.capture.cf=void 0);g.capture.lf=g.se.createMediaStreamSource(l);g.capture.we=g.se.createScriptProcessor(b,a,1);g.capture.we.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.rf=n.inputBuffer,Pa(c,[d]))};g.capture.lf.connect(g.capture.we);g.capture.we.connect(g.se.destination);
g.capture.stream=l}var g=h.SDL2;g.capture.nf=g.se.createBuffer(a,b,g.se.sampleRate);g.capture.nf.getChannelData(0).fill(0);g.capture.cf=setTimeout(function(){g.capture.rf=g.capture.nf;Pa(c,[d])},b/g.se.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},138767:(a,b,c,d)=>{var e=h.SDL2;e.audio.we=
e.se.createScriptProcessor(b,0,a);e.audio.we.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Ef=f.outputBuffer,Pa(c,[d]))};e.audio.we.connect(e.se.destination)},139177:(a,b)=>{for(var c=h.SDL2,d=c.capture.rf.numberOfChannels,e=0;e<d;++e){var f=c.capture.rf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Qa(a+4*g,f[g]);else for(g=0;g<b;++g)Qa(a+4*(g*d+e),
f[g])}},139782:(a,b)=>{for(var c=h.SDL2,d=c.audio.Ef.numberOfChannels,e=0;e<d;++e){var f=c.audio.Ef.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=y[a+(g*d+e<<2)>>2]}},140262:a=>{var b=h.SDL2;if(a){void 0!==b.capture.cf&&clearTimeout(b.capture.cf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.we&&(b.capture.we.onaudioprocess=function(){},b.capture.we.disconnect(),b.capture.we=void 0);void 0!==b.capture.lf&&(b.capture.lf.disconnect(),b.capture.lf=void 0);void 0!==b.capture.nf&&(b.capture.nf=void 0);b.capture=void 0}else void 0!=b.audio.we&&(b.audio.we.disconnect(),b.audio.we=void 0),b.audio=void 0;void 0!==b.se&&void 0===b.audio&&void 0===b.capture&&(b.se.close(),b.se=void 0)},141434:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Xf!==h.canvas&&
(d.Fe=h.createContext(h.canvas,!1,!0),d.Xf=h.canvas);if(d.w!==a||d.h!==b||d.fg!==d.Fe)d.image=d.Fe.createImageData(a,b),d.w=a,d.h=b,d.fg=d.Fe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=q[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.$f!==a&&(d.Zf=new Int32Array(a.buffer),d.ag=new Uint8Array(a.buffer),d.$f=a),a=d.Zf,c=a.length,a.set(q.subarray(b,b+c)),a=d.ag,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Fe.putImageData(d.image,0,0)},142903:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var p=q[e];b[l]=p&255;b[l+1]=p>>8&255;b[l+2]=p>>16&
255;b[l+3]=p>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(q.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,m,d,c.length+1);return d},143892:a=>{h.canvas&&(h.canvas.style.cursor=a?F(m,a):"")},143975:()=>{h.canvas&&(h.canvas.style.cursor="none")},144044:()=>window.innerWidth,144074:()=>window.innerHeight};
function pa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Sa=a=>{for(;0<a.length;)a.shift()(h)},Ta=h.noExitRuntime||!0;
function Qa(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":k[a]=b;break;case "i8":k[a]=b;break;case "i16":va[a>>1]=b;break;case "i32":q[a>>2]=b;break;case "i64":Ha("to do setValue(i64) use WASM_BIGINT");case "float":y[a>>2]=b;break;case "double":z[a>>3]=b;break;case "*":w[a>>2]=b;break;default:Ha(`invalid type for setValue: ${c}`)}}
var Ua=[],Va,G=a=>{var b=Ua[a];b||(a>=Ua.length&&(Ua.length=a+1),Ua[a]=b=Va.get(a));return b},Xa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ya=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Xa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Za=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},$a=a=>{if("/"===a)return"/";a=Ya(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},ab=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(da)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}Ha("initRandomDevice")},bb=a=>(bb=ab())(a),db=(...a)=>
{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:cb;if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Xa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},eb=(a,b)=>{function c(g){for(var l=0;l<g.length&&""===g[l];l++);for(var n=g.length-1;0<=n&&""===g[n];n--);return l>n?[]:g.slice(l,n-l+1)}a=db(a).substr(1);b=db(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,
b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},fb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&fb)return fb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=
String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},gb=[],hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;
b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function ib(a){var b=Array(hb(a)+1);a=E(a,b,0,b.length);b.length=a;return b}var jb=[];function kb(a,b){jb[a]={input:[],output:[],Le:b};lb(a,mb)}
var mb={open(a){var b=jb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close(a){a.tty.Le.fsync(a.tty)},fsync(a){a.tty.Le.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Le.Hf)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Le.Hf(a.tty)}catch(l){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Le.uf)throw new J(60);try{for(var e=0;e<d;e++)a.tty.Le.uf(a.tty,b[c+
e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},nb={Hf(){a:{if(!gb.length){var a=null;if(da){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}gb=ib(a)}a=gb.shift()}return a},uf(a,b){null===b||10===b?(qa(F(a.output,
0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(qa(F(a.output,0)),a.output=[])},hg(){return{xg:25856,zg:5,wg:191,yg:35387,vg:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ig(){return 0},jg(){return[24,80]}},ob={uf(a,b){null===b||10===b?(ea(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(ea(F(a.output,0)),a.output=[])}};
function pb(a,b){var c=a.me?a.me.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.me,a.me=new Uint8Array(b),0<a.oe&&a.me.set(c.subarray(0,a.oe),0))}
var K={Ie:null,ve(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.Ie||(K.Ie={dir:{node:{Ge:K.ke.Ge,ye:K.ke.ye,lookup:K.ke.lookup,mf:K.ke.mf,rename:K.ke.rename,unlink:K.ke.unlink,rmdir:K.ke.rmdir,readdir:K.ke.readdir,symlink:K.ke.symlink},stream:{Te:K.le.Te}},file:{node:{Ge:K.ke.Ge,ye:K.ke.ye},stream:{Te:K.le.Te,read:K.le.read,write:K.le.write,Af:K.le.Af,tf:K.le.tf,Mf:K.le.Mf}},link:{node:{Ge:K.ke.Ge,ye:K.ke.ye,readlink:K.ke.readlink},
stream:{}},Df:{node:{Ge:K.ke.Ge,ye:K.ke.ye},stream:qb}});c=rb(a,b,c,d);L(c.mode)?(c.ke=K.Ie.dir.node,c.le=K.Ie.dir.stream,c.me={}):32768===(c.mode&61440)?(c.ke=K.Ie.file.node,c.le=K.Ie.file.stream,c.oe=0,c.me=null):40960===(c.mode&61440)?(c.ke=K.Ie.link.node,c.le=K.Ie.link.stream):8192===(c.mode&61440)&&(c.ke=K.Ie.Df.node,c.le=K.Ie.Df.stream);c.timestamp=Date.now();a&&(a.me[b]=c,a.timestamp=c.timestamp);return c},Gg(a){return a.me?a.me.subarray?a.me.subarray(0,a.oe):new Uint8Array(a.me):new Uint8Array(0)},
ke:{Ge(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.oe:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Wf=4096;b.blocks=Math.ceil(b.size/b.Wf);return b},ye(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.oe!=b))if(0==
b)a.me=null,a.oe=0;else{var c=a.me;a.me=new Uint8Array(b);c&&a.me.set(c.subarray(0,Math.min(b,a.oe)));a.oe=b}},lookup(){throw sb[44];},mf(a,b,c,d){return K.createNode(a,b,c,d)},rename(a,b,c){if(L(a.mode)){try{var d=tb(b,c)}catch(f){}if(d)for(var e in d.me)throw new J(55);}delete a.parent.me[a.name];a.parent.timestamp=Date.now();a.name=c;b.me[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.me[b];a.timestamp=Date.now()},rmdir(a,b){var c=tb(a,b),d;for(d in c.me)throw new J(55);delete a.me[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.me))b.push(c);return b},symlink(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},le:{read(a,b,c,d,e){var f=a.node.me;if(e>=a.node.oe)return 0;a=Math.min(a.node.oe-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.me||a.me.subarray)){if(f)return a.me=
b.subarray(c,c+d),a.oe=d;if(0===a.oe&&0===e)return a.me=b.slice(c,c+d),a.oe=d;if(e+d<=a.oe)return a.me.set(b.subarray(c,c+d),e),d}pb(a,e+d);if(a.me.subarray&&b.subarray)a.me.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.me[e+f]=b[c+f];a.oe=Math.max(a.oe,e+d);return d},Te(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.oe);if(0>b)throw new J(28);return b},Af(a,b,c){pb(a.node,b+c);a.node.oe=Math.max(a.node.oe,b+c)},tf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);
a=a.node.me;if(e&2||a.buffer!==k.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;Ha();b=void 0;if(!b)throw new J(48);k.set(a,b)}else c=!1,b=a.byteOffset;return{Og:b,tg:c}},Mf(a,b,c,d){K.le.write(a,b,0,d,c,!1);return 0}}},ub=(a,b,c)=>{var d=`al ${a}`;la(a).then(e=>{b(new Uint8Array(e));d&&Ga(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Fa(d)},vb=h.preloadPlugins||[],yb=(a,b,c,d)=>{"undefined"!=typeof wb&&xb();var e=!1;vb.forEach(f=>
{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Ab=(a,b,c,d,e,f,g,l,n,p)=>{function r(x){function v(u){p?.();l||zb(a,b,u,d,e,n);f?.();Ga(A)}yb(x,t,v,()=>{g?.();Ga(A)})||v(x)}var t=b?db(Ya(a+"/"+b)):a,A=`cp ${t}`;Fa(A);"string"==typeof c?ub(c,r,g):r(c)},Bb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Cb=null,Db={},Eb=[],Fb=1,Gb=null,cb="/",Hb=!0,J=class{constructor(a){this.name="ErrnoError";this.ne=a}},sb={},Ib=class{constructor(){this.pe={};this.node=null}get flags(){return this.pe.flags}set flags(a){this.pe.flags=
a}get position(){return this.pe.position}set position(a){this.pe.position=a}},Jb=class{constructor(a,b,c,d){a||=this;this.parent=a;this.ve=a.ve;this.Oe=null;this.id=Fb++;this.name=b;this.mode=c;this.ke={};this.le={};this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get lg(){return L(this.mode)}get kg(){return 8192===(this.mode&61440)}};
function M(a,b={}){a=db(a);if(!a)return{path:"",node:null};b=Object.assign({Gf:!0,vf:0},b);if(8<b.vf)throw new J(32);a=a.split("/").filter(g=>!!g);for(var c=Cb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=tb(c,a[e]);d=Ya(d+"/"+a[e]);c.Oe&&(!f||f&&b.Gf)&&(c=c.Oe.root);if(!f||b.Qe)for(f=0;40960===(c.mode&61440);)if(c=Kb(d),d=db(Za(d),c),c=M(d,{vf:b.vf+1}).node,40<f++)throw new J(32);}return{path:d,node:c}}
function Lb(a){for(var b;;){if(a===a.parent)return a=a.ve.Lf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Gb.length}function Nb(a){var b=Mb(a.parent.id,a.name);a.Ve=Gb[b];Gb[b]=a}function Ob(a){var b=Mb(a.parent.id,a.name);if(Gb[b]===a)Gb[b]=a.Ve;else for(b=Gb[b];b;){if(b.Ve===a){b.Ve=a.Ve;break}b=b.Ve}}
function tb(a,b){var c=L(a.mode)?(c=Pb(a,"x"))?c:a.ke.lookup?0:2:54;if(c)throw new J(c);for(c=Gb[Mb(a.id,b)];c;c=c.Ve){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ke.lookup(a,b)}function rb(a,b,c,d){a=new Jb(a,b,c,d);Nb(a);return a}function L(a){return 16384===(a&61440)}function Qb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Pb(a,b){if(Hb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Rb(a,b){try{return tb(a,b),20}catch(c){}return Pb(a,"wx")}function Sb(a,b,c){try{var d=tb(a,b)}catch(e){return e.ne}if(a=Pb(a,"wx"))return a;if(c){if(!L(d.mode))return 54;if(d===d.parent||Lb(d)===cb)return 10}else if(L(d.mode))return 31;return 0}function Tb(a){a=Eb[a];if(!a)throw new J(8);return a}
function Ub(a,b=-1){a=Object.assign(new Ib,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Eb[b])break a;throw new J(33);}a.fd=b;return Eb[b]=a}function Vb(a,b=-1){a=Ub(a,b);a.le?.Cg?.(a);return a}var qb={open(a){a.le=Db[a.node.rdev].le;a.le.open?.(a)},Te(){throw new J(70);}};function lb(a,b){Db[a]={le:b}}
function Wb(a,b){var c="/"===b;if(c&&Cb)throw new J(10);if(!c&&b){var d=M(b,{Gf:!1});b=d.path;d=d.node;if(d.Oe)throw new J(10);if(!L(d.mode))throw new J(54);}b={type:a,Ng:{},Lf:b,mg:[]};a=a.ve(b);a.ve=b;b.root=a;c?Cb=a:d&&(d.Oe=b,d.ve&&d.ve.mg.push(b));return a}function Xb(a,b,c){var d=M(a,{parent:!0}).node;a=$a(a);if(!a||"."===a||".."===a)throw new J(28);var e=Rb(d,a);if(e)throw new J(e);if(!d.ke.mf)throw new J(63);return d.ke.mf(d,a,b,c)}
function Yb(a,b){return Xb(a,(void 0!==b?b:511)&1023|16384,0)}function $b(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Xb(a,b|8192,c)}function ac(a,b){if(!db(a))throw new J(44);var c=M(b,{parent:!0}).node;if(!c)throw new J(44);b=$a(b);var d=Rb(c,b);if(d)throw new J(d);if(!c.ke.symlink)throw new J(63);c.ke.symlink(c,b,a)}
function bc(a){var b=M(a,{parent:!0}).node;a=$a(a);var c=tb(b,a),d=Sb(b,a,!0);if(d)throw new J(d);if(!b.ke.rmdir)throw new J(63);if(c.Oe)throw new J(10);b.ke.rmdir(b,a);Ob(c)}function cc(a){var b=M(a,{parent:!0}).node;if(!b)throw new J(44);a=$a(a);var c=tb(b,a),d=Sb(b,a,!1);if(d)throw new J(d);if(!b.ke.unlink)throw new J(63);if(c.Oe)throw new J(10);b.ke.unlink(b,a);Ob(c)}function Kb(a){a=M(a).node;if(!a)throw new J(44);if(!a.ke.readlink)throw new J(28);return db(Lb(a.parent),a.ke.readlink(a))}
function dc(a,b){a=M(a,{Qe:!b}).node;if(!a)throw new J(44);if(!a.ke.Ge)throw new J(63);return a.ke.Ge(a)}function ec(a){return dc(a,!0)}function fc(a,b){a="string"==typeof a?M(a,{Qe:!0}).node:a;if(!a.ke.ye)throw new J(63);a.ke.ye(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function gc(a,b,c){if(""===a)throw new J(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ya(a);try{e=M(a,{Qe:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new J(20);}else e=Xb(a,c,0),d=!0;if(!e)throw new J(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!L(e.mode))throw new J(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:L(e.mode)&&("r"!==Qb(b)||b&512)?31:Pb(e,Qb(b)):44))throw new J(c);if(b&512&&!d){c=e;c="string"==typeof c?M(c,{Qe:!0}).node:c;if(!c.ke.ye)throw new J(63);if(L(c.mode))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(d=Pb(c,"w"))throw new J(d);c.ke.ye(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Ub({node:e,path:Lb(e),flags:b,seekable:!0,position:0,le:e.le,pg:[],error:!1});e.le.open&&e.le.open(e);!h.logReadFiles||b&1||(hc||={},a in hc||(hc[a]=1));return e}
function ic(a){if(null===a.fd)throw new J(8);a.Re&&(a.Re=null);try{a.le.close&&a.le.close(a)}catch(b){throw b;}finally{Eb[a.fd]=null}a.fd=null}function jc(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.le.Te)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.le.Te(a,b,c);a.pg=[];return a.position}
function kc(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(L(a.node.mode))throw new J(31);if(!a.le.write)throw new J(28);a.seekable&&a.flags&1024&&jc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new J(70);b=a.le.write(a,b,c,d,e,f);g||(a.position+=b);return b}var lc;
function mc(a,b){a="string"==typeof a?a:Lb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ya(a+"/"+c);try{Yb(d)}catch(e){}a=d}}return d}function nc(a,b,c,d){a=Ya(("string"==typeof a?a:Lb(a))+"/"+b);c=Bb(c,d);return Xb(a,(void 0!==c?c:438)&4095|32768,0)}
function zb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Lb(a),g=b?Ya(a+"/"+b):a);a=Bb(d,e);g=Xb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}fc(g,a|146);b=gc(g,577);kc(b,c,0,c.length,0,f);ic(b);fc(g,a)}}
function oc(a,b,c,d){a=Ya(("string"==typeof a?a:Lb(a))+"/"+b);b=Bb(!!c,!!d);oc.Jf||(oc.Jf=64);var e=oc.Jf++<<8|0;lb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,n){for(var p=0,r=0;r<n;r++){try{var t=c()}catch(A){throw new J(29);}if(void 0===t&&0===p)throw new J(6);if(null===t||void 0===t)break;p++;g[l+r]=t}p&&(f.node.timestamp=Date.now());return p},write(f,g,l,n){for(var p=0;p<n;p++)try{d(g[l+p])}catch(r){throw new J(29);}n&&(f.node.timestamp=Date.now());return p}});return $b(a,
b,e)}function pc(a){if(!(a.kg||a.lg||a.link||a.me)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.me=ma(a.url),a.oe=a.me.length}catch(b){throw new J(29);}}}
function qc(a,b,c,d,e){class f{constructor(){this.af=!1;this.pe=[];this.Se=void 0;this.Nf=this.Of=0}get(r){if(!(r>this.length-1||0>r)){var t=r%this.chunkSize;return this.Se(r/this.chunkSize|0)[t]}}ng(r){this.Se=r}Qf(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var t=Number(r.getResponseHeader("Content-length")),A,x=(A=r.getResponseHeader("Accept-Ranges"))&&"bytes"===A;r=(A=r.getResponseHeader("Content-Encoding"))&&
"gzip"===A;var v=1048576;x||(v=t);var u=this;u.ng(H=>{var O=H*v,aa=(H+1)*v-1;aa=Math.min(aa,t-1);if("undefined"==typeof u.pe[H]){var Wa=u.pe;if(O>aa)throw Error("invalid range ("+O+", "+aa+") or no bytes requested!");if(aa>t-1)throw Error("only "+t+" bytes available! programmer error!");var I=new XMLHttpRequest;I.open("GET",c,!1);t!==v&&I.setRequestHeader("Range","bytes="+O+"-"+aa);I.responseType="arraybuffer";I.overrideMimeType&&I.overrideMimeType("text/plain; charset=x-user-defined");I.send(null);
if(!(200<=I.status&&300>I.status||304===I.status))throw Error("Couldn't load "+c+". Status: "+I.status);O=void 0!==I.response?new Uint8Array(I.response||[]):ib(I.responseText||"");Wa[H]=O}if("undefined"==typeof u.pe[H])throw Error("doXHR failed!");return u.pe[H]});if(r||!t)v=t=1,v=t=this.Se(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Of=t;this.Nf=v;this.af=!0}get length(){this.af||this.Qf();return this.Of}get chunkSize(){this.af||this.Qf();return this.Nf}}
if("undefined"!=typeof XMLHttpRequest){if(!ca)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;var l=void 0}else l=c,g=void 0;var n=nc(a,b,d,e);g?n.me=g:l&&(n.me=null,n.url=l);Object.defineProperties(n,{oe:{get:function(){return this.me.length}}});var p={};Object.keys(n.le).forEach(r=>{var t=n.le[r];p[r]=(...A)=>{pc(n);return t(...A)}});p.read=(r,t,A,x,v)=>{pc(n);r=r.node.me;if(v>=r.length)t=0;else{x=Math.min(r.length-
v,x);if(r.slice)for(var u=0;u<x;u++)t[A+u]=r[v+u];else for(u=0;u<x;u++)t[A+u]=r.get(v+u);t=x}return t};p.tf=()=>{pc(n);Ha();throw new J(48);};n.le=p;return n}var N={},hc;function rc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?cb:Tb(a).path;if(0==b.length){if(!c)throw new J(44);return a}return Ya(a+"/"+b)}
function sc(a,b,c){a=a(b);q[c>>2]=a.dev;q[c+4>>2]=a.mode;w[c+8>>2]=a.nlink;q[c+12>>2]=a.uid;q[c+16>>2]=a.gid;q[c+20>>2]=a.rdev;C=[a.size>>>0,(B=a.size,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];q[c+24>>2]=C[0];q[c+28>>2]=C[1];q[c+32>>2]=4096;q[c+36>>2]=a.blocks;b=a.atime.getTime();var d=a.mtime.getTime(),e=a.ctime.getTime();C=[Math.floor(b/1E3)>>>0,(B=Math.floor(b/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>
0))/4294967296)>>>0:0)];q[c+40>>2]=C[0];q[c+44>>2]=C[1];w[c+48>>2]=b%1E3*1E3;C=[Math.floor(d/1E3)>>>0,(B=Math.floor(d/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];q[c+56>>2]=C[0];q[c+60>>2]=C[1];w[c+64>>2]=d%1E3*1E3;C=[Math.floor(e/1E3)>>>0,(B=Math.floor(e/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];q[c+72>>2]=C[0];q[c+76>>2]=C[1];w[c+80>>2]=e%1E3*1E3;C=[a.ino>>>0,(B=a.ino,1<=+Math.abs(B)?
0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];q[c+88>>2]=C[0];q[c+92>>2]=C[1];return 0}var tc=void 0;
function uc(a,b){if(1===a.type&&a.te)throw new J(53);var c=a.We.shift();if(!c){if(1===a.type){a=a.Je[a.xe+":"+a.Ce];if(!a)throw new J(53);if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null}throw new J(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var g={buffer:new Uint8Array(f,e,b),qe:c.qe,port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.We.unshift(c));return g}
function vc(a,b,c,d,e,f){if(2===a.type){if(void 0===e||void 0===f)e=a.xe,f=a.Ce;if(void 0===e||void 0===f)throw new J(17);}else e=a.xe,f=a.Ce;var g=a.Je[e+":"+f];if(1===a.type){if(!g||g.socket.readyState===g.socket.CLOSING||g.socket.readyState===g.socket.CLOSED)throw new J(53);if(g.socket.readyState===g.socket.CONNECTING)throw new J(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(2===a.type&&(!g||g.socket.readyState!==g.socket.OPEN))return g&&g.socket.readyState!==g.socket.CLOSING&&
g.socket.readyState!==g.socket.CLOSED||(g=wc(a,e,f)),g.gf.push(b),d;try{return g.socket.send(b),d}catch(l){throw new J(28);}}
function xc(a,b){function c(){h.websocket.emit("open",a.stream.fd);try{for(var f=b.gf.shift();f;)b.socket.send(f),f=b.gf.shift()}catch(g){b.socket.close()}}function d(f){if("string"==typeof f)f=(new TextEncoder).encode(f);else{void 0!==f.byteLength||Ha();if(0==f.byteLength)return;f=new Uint8Array(f)}var g=e;e=!1;g&&10===f.length&&255===f[0]&&255===f[1]&&255===f[2]&&255===f[3]&&112===f[4]&&111===f[5]&&114===f[6]&&116===f[7]?(f=f[8]<<8|f[9],delete a.Je[b.qe+":"+b.port],b.port=f,a.Je[b.qe+":"+b.port]=
b):(a.We.push({qe:b.qe,port:b.port,data:f}),h.websocket.emit("message",a.stream.fd))}var e=!0;da?(b.socket.on("open",c),b.socket.on("message",function(f,g){g&&d((new Uint8Array(f)).buffer)}),b.socket.on("close",function(){h.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;h.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=function(){h.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(f){d(f.data)},
b.socket.onerror=function(){a.error=14;h.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})}
function wc(a,b,c){if("object"==typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e=h.websocket&&"object"===typeof h.websocket,f="ws://";e&&"string"===typeof h.websocket.url&&(f=h.websocket.url);if("ws://"===f||"wss://"===f){var g=b.split("/");f=f+g[0]+":"+c+"/"+g.slice(1).join("/")}g="binary";
e&&"string"===typeof h.websocket.subprotocol&&(g=h.websocket.subprotocol);var l=void 0;"null"!==g&&(l=g=g.replace(/^ +| +$/g,"").split(/ *, */));e&&null===h.websocket.subprotocol&&(l=void 0);d=new (da?require("ws"):WebSocket)(f,l);d.binaryType="arraybuffer"}catch(n){throw new J(23);}b={qe:b,port:c,socket:d,gf:[]};a.Je[b.qe+":"+b.port]=b;xc(a,b);2===a.type&&"undefined"!=typeof a.Ye&&b.gf.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.Ye&65280)>>8,a.Ye&255]));return b}
var yc={ve(){h.websocket=h.websocket&&"object"===typeof h.websocket?h.websocket:{};h.websocket.pf={};h.websocket.on=function(a,b){"function"===typeof b&&(this.pf[a]=b);return this};h.websocket.emit=function(a,b){"function"===typeof this.pf[a]&&this.pf[a].call(this,b)};return rb(null,"/",16895,0)},createSocket(a,b,c){b&=-526337;if(1==b&&c&&6!=c)throw new J(66);a={family:a,type:b,protocol:c,te:null,error:null,Je:{},pending:[],We:[],Pe:yc.rg};b=yc.He();c=rb(yc.root,b,49152,0);c.Xe=a;b=Ub({path:b,node:c,
flags:2,seekable:!1,le:yc.le});a.stream=b;return a},le:{bf(a){a=a.node.Xe;return a.Pe.bf(a)},$e(a,b,c){a=a.node.Xe;return a.Pe.$e(a,b,c)},read(a,b,c,d){a=uc(a.node.Xe,d);if(!a)return 0;b.set(a.buffer,c);return a.buffer.length},write(a,b,c,d){return vc(a.node.Xe,b,c,d)},close(a){a=a.node.Xe;a.Pe.close(a)}},He(){yc.He.current||(yc.He.current=0);return"socket["+yc.He.current++ +"]"},rg:{bf(a){if(1===a.type&&a.te)return a.pending.length?65:0;var b=0,c=1===a.type?a.Je[a.xe+":"+a.Ce]:null;if(a.We.length||
!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=65;if(!c||c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},$e(a,b,c){switch(b){case 21531:return b=0,a.We.length&&(b=a.We[0].data.length),q[c>>2]=b,0;default:return 28}},close(a){if(a.te){try{a.te.close()}catch(e){}a.te=null}for(var b=Object.keys(a.Je),c=0;c<b.length;c++){var d=a.Je[b[c]];try{d.socket.close()}catch(e){}delete a.Je[d.qe+
":"+d.port]}return 0},bind(a,b,c){if("undefined"!=typeof a.wf||"undefined"!=typeof a.Ye)throw new J(28);a.wf=b;a.Ye=c;if(2===a.type){a.te&&(a.te.close(),a.te=null);try{a.Pe.listen(a,0)}catch(d){if("ErrnoError"!==d.name)throw d;if(138!==d.ne)throw d;}}},connect(a,b,c){if(a.te)throw new J(138);if("undefined"!=typeof a.xe&&"undefined"!=typeof a.Ce){var d=a.Je[a.xe+":"+a.Ce];if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new J(7);throw new J(30);}}b=wc(a,b,c);a.xe=b.qe;a.Ce=b.port;throw new J(26);
},listen(a){if(!da)throw new J(138);if(a.te)throw new J(28);var b=require("ws").Server;a.te=new b({host:a.wf,port:a.Ye});h.websocket.emit("listen",a.stream.fd);a.te.on("connection",function(c){if(1===a.type){var d=yc.createSocket(a.family,a.type,a.protocol);c=wc(d,c);d.xe=c.qe;d.Ce=c.port;a.pending.push(d);h.websocket.emit("connection",d.stream.fd)}else wc(a,c),h.websocket.emit("connection",a.stream.fd)});a.te.on("close",function(){h.websocket.emit("close",a.stream.fd);a.te=null});a.te.on("error",
function(){a.error=23;h.websocket.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},accept(a){if(!a.te||!a.pending.length)throw new J(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Hg(a,b){if(b){if(void 0===a.xe||void 0===a.Ce)throw new J(53);b=a.xe;a=a.Ce}else b=a.wf||0,a=a.Ye||0;return{qe:b,port:a}}}},zc=a=>{a=(a=Eb[a])&&49152===(a.node.mode&49152)?a.node.Xe:null;if(!a)throw new J(8);return a},Ac=a=>{a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);
if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},Cc=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-
3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"==typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Bc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},Dc=(a,b,c,d,e)=>{switch(b){case 2:c=Ac(c);m.fill(0,a,a+16);e&&(q[e>>2]=16);va[a>>1]=b;q[a+4>>2]=c;va[a+2>>1]=Bc(d);break;case 10:c=Cc(c);m.fill(0,a,a+28);e&&(q[e>>2]=28);
q[a>>2]=b;q[a+8>>2]=c[0];q[a+12>>2]=c[1];q[a+16>>2]=c[2];q[a+20>>2]=c[3];va[a+2>>1]=Bc(d);break;default:return 5}return 0},Ec=1,Fc={},Gc={};function Hc(a){var b=Ac(a);if(null!==b)return a;b=Cc(a);if(null!==b)return a;Fc[a]?b=Fc[a]:(b=Ec++,65535>b||Ha("exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),Gc[b]=a,Fc[a]=b);return b}
var Ic=a=>(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255),Kc=a=>{var b="",c,d=0,e=0,f=0,g=0;a=[a[0]&65535,a[0]>>16,a[1]&65535,a[1]>>16,a[2]&65535,a[2]>>16,a[3]&65535,a[3]>>16];var l=!0;for(c=0;5>c;c++)if(0!==a[c]){l=!1;break}if(l){c=Ic(a[6]|a[7]<<16);if(-1===a[5])return"::ffff:"+c;if(0===a[5])return"0.0.0.0"===c&&(c=""),"0.0.0.1"===c&&(c="1"),"::"+c}for(c=0;8>c;c++)0===a[c]&&(1<c-e&&(g=0),e=c,g++),g>d&&(d=g,f=c-d+1);for(c=0;8>c;c++)1<d&&0===a[c]&&c>=f&&c<f+d?c===f&&(b+=":",0===f&&(b+=":")):
(b+=Number(Jc(a[c]&65535)).toString(16),b+=7>c?":":"");return b},Lc=(a,b)=>{var c=va[a>>1],d=Jc(wa[a+2>>1]);switch(c){case 2:if(16!==b)return{ne:28};a=q[a+4>>2];a=Ic(a);break;case 10:if(28!==b)return{ne:28};a=[q[a+8>>2],q[a+12>>2],q[a+16>>2],q[a+20>>2]];a=Kc(a);break;default:return{ne:5}}return{family:c,qe:a,port:d}},Mc=(a,b,c)=>{if(c&&0===a)return null;a=Lc(a,b);if(a.ne)throw new J(a.ne);b=a.qe;a.qe=(Gc[b]?Gc[b]:null)||a.qe;return a};function Nc(){var a=q[+tc>>2];tc+=4;return a}
var P={Ae:8192,ve(){return rb(null,"/",16895,0)},le:{bf(a){var b=a.node.pipe;if(1===(a.flags&2097155))return 260;if(0<b.re.length)for(a=0;a<b.re.length;a++){var c=b.re[a];if(0<c.offset-c.Ee)return 65}return 0},$e(){return 28},fsync(){return 28},read(a,b,c,d){a=a.node.pipe;for(var e=0,f=0;f<a.re.length;f++){var g=a.re[f];e+=g.offset-g.Ee}b=b.subarray(c,c+d);if(0>=d)return 0;if(0==e)throw new J(6);c=d=Math.min(e,d);for(f=e=0;f<a.re.length;f++){g=a.re[f];var l=g.offset-g.Ee;if(d<=l){var n=g.buffer.subarray(g.Ee,
g.offset);d<l?(n=n.subarray(0,d),g.Ee+=d):e++;b.set(n);break}else n=g.buffer.subarray(g.Ee,g.offset),b.set(n),b=b.subarray(n.byteLength),d-=n.byteLength,e++}e&&e==a.re.length&&(e--,a.re[e].offset=0,a.re[e].Ee=0);a.re.splice(0,e);return c},write(a,b,c,d){a=a.node.pipe;b=b.subarray(c,c+d);c=b.byteLength;if(0>=c)return 0;0==a.re.length?(d={buffer:new Uint8Array(P.Ae),offset:0,Ee:0},a.re.push(d)):d=a.re[a.re.length-1];d.offset<=P.Ae||Ha();var e=P.Ae-d.offset;if(e>=c)return d.buffer.set(b,d.offset),d.offset+=
c,c;0<e&&(d.buffer.set(b.subarray(0,e),d.offset),d.offset+=e,b=b.subarray(e,b.byteLength));d=b.byteLength/P.Ae|0;e=b.byteLength%P.Ae;for(var f=0;f<d;f++){var g={buffer:new Uint8Array(P.Ae),offset:P.Ae,Ee:0};a.re.push(g);g.buffer.set(b.subarray(0,P.Ae));b=b.subarray(P.Ae,b.byteLength)}0<e&&(g={buffer:new Uint8Array(P.Ae),offset:b.byteLength,Ee:0},a.re.push(g),g.buffer.set(b));return c},close(a){a=a.node.pipe;a.Tf--;0===a.Tf&&(a.re=null)}},He(){P.He.current||(P.He.current=0);return"pipe["+P.He.current++ +
"]"}},Oc=[0,31,60,91,121,152,182,213,244,274,305,335],Pc=[0,31,59,90,120,151,181,212,243,273,304,334],Qc={},Rc=a=>{a instanceof pa||"unwind"==a||ja(1,a)},Sc=0,Tc=a=>{ua=a;Ta||0<Sc||(h.onExit?.(a),ta=!0);ja(a,new pa(a))},Uc=a=>{ua=a;Tc(a)},Vc=a=>{if(!ta)try{if(a(),!(Ta||0<Sc))try{ua=a=ua,Tc(a)}catch(b){Rc(b)}}catch(b){Rc(b)}},Wc;Wc=()=>performance.now();
var fd=(a,b)=>{Xc=a;Yc=b;if(Zc)if($c||=!0,0==a)ad=function(){var d=Math.max(0,bd+b-Wc())|0;setTimeout(cd,d)};else if(1==a)ad=function(){dd(cd)};else if(2==a){if("undefined"==typeof ed)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);ed=function(d){c.push(d);if(ca){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate",
"*")}}else ed=setImmediate;ad=function(){ed(cd)}}},pd=(a,b,c,d,e)=>{Zc=a;jd=d;var f=kd;$c=!1;cd=function(){if(!ta)if(0<ld.length){var g=ld.shift();g.Fg(g.ug);if(md){var l=md,n=0==l%1?l-1:Math.floor(l);md=g.Bg?n:(8*l+(n+.5))/9}h.setStatus&&(g=h.statusMessage||"Please wait...",l=md,n=nd.Dg,l?l<n?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(g):h.setStatus(""));f<kd||setTimeout(cd,0)}else f<kd||(od=od+1|0,1==Xc&&1<Yc&&0!=od%Yc?ad():(0==Xc&&(bd=Wc()),ta||h.preMainLoop&&!1===
h.preMainLoop()||(Vc(a),h.postMainLoop?.()),f<kd||("object"==typeof SDL&&SDL.audio?.Pg?.(),ad())))};e||(b&&0<b?fd(0,1E3/b):fd(1,1),ad());if(c)throw"unwind";},qd=a=>{setTimeout(()=>{Vc(a)},1E4)},$c=!1,ad=null,kd=0,Zc=null,jd=0,Xc=0,Yc=0,od=0,ld=[],nd={},bd,cd,md,rd=!1,sd=!1,td=[];
function xb(){function a(){sd=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!ud){ud=!0;vb.push({canHandle:function(c){return!h.Mg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:vd(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:vd(d)}));var l=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=document.createElement("canvas");
p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(l);e?.(c)};n.onerror=()=>{ea(`Image ${l} could not be decoded`);f?.()};n.src=l}});vb.push({canHandle:function(c){return!h.Lg&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:vd(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){ea(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",r=0,t=0,A=0;A<c.length;A++)for(r=r<<8|c[A],t+=8;6<=t;){var x=r>>t-6&63;t-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==t?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],p+="=="):4==t&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=l;qd(()=>{f(n)})}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!sd&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var wd=!1,xd=void 0,yd=void 0;function zd(){if(!rd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Ad=0;
function dd(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ad)Ad=b+1E3/60;else for(;b+2>=Ad;)Ad+=1E3/60;setTimeout(a,Math.max(Ad-b,0))}}function vd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Bd=[];function Cd(){var a=h.canvas;Bd.forEach(b=>b(a.width,a.height))}
function Dd(a,b,c){b&&c?(a.sg=b,a.eg=c):(b=a.sg,c=a.eg);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}yd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var wb={},ed,ud,Q=12288,Ed=!1,Fd=0,Gd=0,Hd=0,R={alpha:!1,depth:!1,stencil:!1,antialias:!1},Id={},Jd,Kd=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Ld=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Md=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Nd=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Od=1,Pd=[],S=[],Qd=[],Rd=[],Sd=[],T=[],Td=[],Ud=[],Vd=[],Wd={},Xd=4,Yd=0,Zd=a=>{for(var b=Od++,c=a.length;c<b;c++)a[c]=null;return b},$d=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=U[c](),g=f&&Zd(d);f?(f.name=g,d[g]=f):V||=1282;q[b+4*e>>2]=g}},be=(a,b)=>{a.pe||(a.pe=a.getContext,a.getContext=function(d,e){e=a.pe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?ae(c,b):0},ae=(a,b)=>
{var c=Zd(Ud),d={handle:c,attributes:b,version:b.Kf,Me:a};a.canvas&&(a.canvas.Ze=d);Ud[c]=d;("undefined"==typeof b.cg||b.cg)&&ce(d);return c},ee=a=>{de=Ud[a];h.Fe=U=de?.Me},ce=a=>{a||=de;if(!a.gg){a.gg=!0;var b=a.Me;Kd(b);Ld(b);Md(b);b.Ke=b.getExtension("EXT_disjoint_timer_query");b.Kg=b.getExtension("WEBGL_multi_draw");Nd(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},fe={},V,de,ge=a=>{var b=hb(a)+1,c=D(b);c&&E(a,m,c,b);return c},he=[],ie=(a,b)=>{he.length=
0;for(var c;c=m[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;he.push(112==c?w[b>>2]:105==c?q[b>>2]:z[b>>3]);b+=d?8:4}return he},je=0,ke=[];function le(a,b,c){function d(g,l){if(g.length!=l.length)return!1;for(var n in g)if(g[n]!=l[n])return!1;return!0}for(var e in ke){var f=ke[e];if(f.yf==a&&d(f.Bf,c))return}ke.push({yf:a,Rf:b,Bf:c});ke.sort((g,l)=>g.Rf<l.Rf)}function me(a){for(var b=0;b<ke.length;++b)ke[b].yf==a&&(ke.splice(b,1),--b)}
function ne(){return navigator.userActivation?navigator.userActivation.isActive:je&&oe.ef}function pe(){if(ne())for(var a=0;a<ke.length;++a){var b=ke[a];ke.splice(a,1);--a;b.yf(...b.Bf)}}var qe=[];function re(a){var b=qe[a];b.target.removeEventListener(b.ue,b.Ff,b.ze);qe.splice(a,1)}
function se(a){if(!a.target)return-4;if(a.Be)a.Ff=function(c){++je;oe=a;pe();a.De(c);pe();--je},a.target.addEventListener(a.ue,a.Ff,a.ze),qe.push(a);else for(var b=0;b<qe.length;++b)qe[b].target==a.target&&qe[b].ue==a.ue&&re(b--);return 0}function te(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}function ue(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var ve={},oe,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie={},Je=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],W=a=>{a=2<a?a?F(m,a):"":a;return Je[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Le=a=>{var b=hb(a)+1,c=Ke(b);E(a,m,c,b);return c},Pe=a=>{var b=Me(),c=Ke(8),d=c+4;a=Le(a.id);if(a=W(a))q[c>>2]=a.width,q[d>>2]=a.height;c=[q[c>>2],q[d>>2]];Oe(b);return c},Qe=(a,b,c)=>{a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0},Re=(a,b,c)=>{if(a.Ag){var d=
Me();a=Le(a.id);Qe(a,b,c);Oe(d)}else a.width=b,a.height=c},Se=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Re(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=r,a.style.paddingTop=t,a.style.paddingBottom=A,a.style.marginLeft=
x,a.style.marginRight=v,a.style.marginTop=u,a.style.marginBottom=H,document.body.style.margin=O,document.documentElement.style.overflow=aa,document.body.scroll=Wa,a.style.Ne=I,a.Ze&&a.Ze.Me.viewport(0,0,d,e),Ie.ff&&G(Ie.ff)(37,0,Ie.Cf))}var c=Pe(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,r=a.style.paddingRight,t=a.style.paddingTop,A=a.style.paddingBottom,x=a.style.marginLeft,v=a.style.marginRight,u=a.style.marginTop,
H=a.style.marginBottom,O=document.body.style.margin,aa=document.documentElement.style.overflow,Wa=document.body.scroll,I=a.style.Ne;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Te=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Ue=a=>0>Je.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Ve=(a,b)=>{if(0!=b.xf||0!=b.qf){Se(a);var c=b.og?innerWidth:screen.width,d=b.og?innerHeight:screen.height,
e=Ue(a),f=e.width;e=e.height;var g=Pe(a),l=g[0];g=g[1];3==b.xf?(Te(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.xf&&(c*g<l*d?(f=g*c/l,Te(a,(d-f)/2,0),d=f):(f=l*d/g,Te(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.dg&&(a.style.Ne="optimizeSpeed",a.style.Ne="-moz-crisp-edges",a.style.Ne="-o-crisp-edges",a.style.Ne="-webkit-optimize-contrast",a.style.Ne=
"optimize-contrast",a.style.Ne="crisp-edges",a.style.Ne="pixelated");f=2==b.qf?devicePixelRatio:1;0!=b.qf&&(c=c*f|0,d=d*f|0,Re(a,c,d),a.Ze&&a.Ze.Me.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ue()?-3:-1;Ie=b;b.ff&&G(b.ff)(37,0,b.Cf);return 0},We=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Xe=(a,b)=>{z[a>>3]=b.timestamp;
for(var c=0;c<b.axes.length;++c)z[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)z[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)k[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];k[a+1104]=b.connected;q[a+1108>>2]=b.index;q[a+8>>2]=b.axes.length;q[a+12>>2]=b.buttons.length;E(b.id,m,a+1112,64);E(b.mapping,m,a+1176,64)},Ye=[],Ze=(a,b,c,d,e,f,g,l)=>{b=S[b];if(a=U[a](b,c))d=l&&E(a.name,m,l,d),e&&(q[e>>2]=
d),f&&(q[f>>2]=a.size),g&&(q[g>>2]=a.type)},$e=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(V||=1280);return;case 36345:d=0;break;case 34466:var e=U.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=U.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:V||=
1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:k[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){V||=1280;ea(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:V||=1280;ea(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;w[b>>2]=c;w[b+4>>2]=(c-w[b>>2])/4294967296;break;case 0:q[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:k[b]=d?1:0}}else V||=1281},af=(a,b,c)=>{if(c){a=U.Ke.getQueryObjectEXT(Vd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d;w[c+4>>2]=(d-w[c>>2])/4294967296}else V||=1281},bf=(a,b,c)=>{if(c){a=U.Ke.getQueryObjectEXT(Vd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;q[c>>2]=d}else V||=1281};function cf(){var a=Nd(U);return a=a.concat(a.map(b=>"GL_"+b))}
var df=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),ef=a=>{var b=a.df,c=a.Vf,d;if(!b)for(a.df=b={},a.Uf={},d=0;d<U.getProgramParameter(a,35718);++d){var e=U.getActiveUniform(a,d);var f=e.name;e=e.size;var g=df(f);g=0<g?f.slice(0,g):f;var l=a.zf;a.zf+=e;c[g]=[e,l];for(f=0;f<e;++f)b[l]=f,a.Uf[l++]=g}},X=a=>{var b=U.Yf;if(b){var c=b.df[a];"number"==typeof c&&(b.df[a]=c=U.getUniformLocation(b,b.Uf[a]+(0<c?`[${c}]`:"")));return c}V||=1282},ff=(a,b,c,d)=>{if(c)if(a=S[a],ef(a),a=U.getUniform(a,X(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else V||=1281},gf=(a,b,c,d)=>{if(c)if(a=U.getVertexAttrib(a,b),34975==b)q[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:y[c>>2]=a;break;case 5:q[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:q[c+
4*b>>2]=Math.fround(a[b])}else V||=1281},hf=(a,b,c,d,e)=>{a-=5120;a=1==a?m:4==a?q:6==a?y:5==a||28922==a?w:wa;b=d*((Yd||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Xd-1&-Xd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},jf=[],kf=[],lf=(a,b)=>{if(!ue())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?ne()?Ve(a,b):b.bg?(le(Ve,1,[a,b]),1):-2:-3:-4},mf=()=>{try{if(navigator.getGamepads)return(we=navigator.getGamepads())?
0:-1}catch(a){navigator.getGamepads=null}return-1},nf=(a,b)=>{var c={target:W(2),ue:"beforeunload",Be:b,De:(d=event)=>{var e=G(b)(28,0,a);e&&=e?F(m,e):"";if(e)return d.preventDefault(),d.returnValue=e},ze:!0};return se(c)},of=(a,b,c,d,e,f)=>{xe||=D(256);a={target:W(a),ue:f,Be:d,De:(g=event)=>{var l=g.target.id?g.target.id:"",n=xe;E(te(g.target),m,n+0,128);E(l,m,n+128,128);G(d)(e,n,b)&&g.preventDefault()},ze:c};return se(a)},pf=(a,b,c,d,e)=>{ze||=D(276);return se({target:a,ue:e,Be:d,De:(f=event)=>
{var g=ze,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;k[g]=n;k[g+1]=ue();var p=n?l:ye,r=p?.id||"";E(te(p),m,g+2,128);E(r,m,g+130,128);q[g+260>>2]=p?p.clientWidth:0;q[g+264>>2]=p?p.clientHeight:0;q[g+268>>2]=screen.width;q[g+272>>2]=screen.height;n&&(ye=l);G(d)(19,g,b)&&f.preventDefault()},ze:c})},qf=(a,b,c,d,e)=>{Ae||=D(1240);b={target:W(2),ef:!0,ue:e,Be:c,De:(f=event)=>{var g=Ae;Xe(g,f.gamepad);G(c)(d,g,a)&&f.preventDefault()},
ze:b};return se(b)},rf=(a,b,c,d,e,f)=>{Be||=D(160);a={target:W(a),ue:f,Be:d,De:g=>{var l=Be;z[l>>3]=g.timeStamp;var n=l>>2;q[n+2]=g.location;k[n+12]=g.ctrlKey;k[n+13]=g.shiftKey;k[n+14]=g.altKey;k[n+15]=g.metaKey;k[n+16]=g.repeat;q[n+5]=g.charCode;q[n+6]=g.keyCode;q[n+7]=g.which;E(g.key||"",m,l+32,32);E(g.code||"",m,l+64,32);E(g.char||"",m,l+96,32);E(g.locale||"",m,l+128,32);G(d)(e,l,b)&&g.preventDefault()},ze:c};return se(a)},sf=(a,b,c)=>{z[a>>3]=b.timeStamp;a>>=2;q[a+2]=b.screenX;q[a+3]=b.screenY;
q[a+4]=b.clientX;q[a+5]=b.clientY;k[a+24]=b.ctrlKey;k[a+25]=b.shiftKey;k[a+26]=b.altKey;k[a+27]=b.metaKey;va[2*a+14]=b.button;va[2*a+15]=b.buttons;q[a+8]=b.movementX;q[a+9]=b.movementY;c=Ue(c);q[a+10]=b.clientX-(c.left|0);q[a+11]=b.clientY-(c.top|0)},tf=(a,b,c,d,e,f)=>{Ce||=D(64);a=W(a);return se({target:a,ef:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ue:f,Be:d,De:(g=event)=>{sf(Ce,g,a);G(d)(e,Ce,b)&&g.preventDefault()},ze:c})},uf=(a,b,c,d,e)=>{De||=D(257);return se({target:a,ue:e,Be:d,De:(f=
event)=>{var g=De,l=document.pointerLockElement||document.pe||document.af||document.Se;k[g]=!!l;var n=l?.id||"";E(te(l),m,g+1,128);E(n,m,g+129,128);G(d)(20,g,b)&&f.preventDefault()},ze:c})},vf=(a,b,c,d)=>{Ee||=D(36);a=W(a);return se({target:a,ue:"resize",Be:d,De:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=Ee;q[g>>2]=0;q[g+4>>2]=f.clientWidth;q[g+8>>2]=f.clientHeight;q[g+12>>2]=innerWidth;q[g+16>>2]=innerHeight;q[g+20>>2]=outerWidth;q[g+24>>2]=outerHeight;q[g+28>>2]=pageXOffset|0;q[g+
32>>2]=pageYOffset|0;G(d)(10,g,b)&&e.preventDefault()}}},ze:c})},wf=(a,b,c,d,e,f)=>{Fe||=D(1552);a=W(a);return se({target:a,ef:"touchstart"==f||"touchend"==f,ue:f,Be:d,De:g=>{for(var l,n={},p=g.touches,r=0;r<p.length;++r)l=p[r],l.If=l.Pf=0,n[l.identifier]=l;for(r=0;r<g.changedTouches.length;++r)l=g.changedTouches[r],l.If=1,n[l.identifier]=l;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].Pf=1;p=Fe;z[p>>3]=g.timeStamp;var t=p>>2;k[t+12]=g.ctrlKey;k[t+13]=g.shiftKey;k[t+14]=g.altKey;
k[t+15]=g.metaKey;t+=4;var A=Ue(a),x=0;for(r in n)if(l=n[r],q[t]=l.identifier,q[t+1]=l.screenX,q[t+2]=l.screenY,q[t+3]=l.clientX,q[t+4]=l.clientY,q[t+5]=l.pageX,q[t+6]=l.pageY,k[t+28]=l.If,k[t+29]=l.Pf,q[t+8]=l.clientX-(A.left|0),q[t+9]=l.clientY-(A.top|0),t+=12,31<++x)break;q[p+8>>2]=x;G(d)(e,p,b)&&g.preventDefault()},ze:c})},xf=(a,b,c)=>{var d=Je[1];Ge||=D(8);return se({target:d,ue:"visibilitychange",Be:c,De:(e=event)=>{var f=Ge,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);
k[f]=document.hidden;q[f+4>>2]=g;G(c)(21,f,a)&&e.preventDefault()},ze:b})},yf=(a,b,c,d)=>{He||=D(96);return se({target:a,ef:!0,ue:"wheel",Be:d,De:(e=event)=>{var f=He;sf(f,e,a);z[f+64>>3]=e.deltaX;z[f+72>>3]=e.deltaY;z[f+80>>3]=e.deltaZ;q[f+88>>2]=e.deltaMode;G(d)(9,f,b)&&e.preventDefault()},ze:c})},zf={},Bf=()=>{if(!Af){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+
".UTF-8",_:ia||"./this.program"},b;for(b in zf)void 0===zf[b]?delete a[b]:a[b]=zf[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Af=c}return Af},Af,Cf=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Oa=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Cf(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Pa=(a,b=[])=>{if("vi".includes("j")){var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)}else G(a)(...b)};
[44].forEach(a=>{sb[a]=new J(a);sb[a].stack="<generic error, no stack>"});Gb=Array(4096);Wb(K,"/");Yb("/tmp");Yb("/home");Yb("/home/web_user");(function(){Yb("/dev");lb(259,{read:()=>0,write:(d,e,f,g)=>g});$b("/dev/null",259);kb(1280,nb);kb(1536,ob);$b("/dev/tty",1280);$b("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=bb(a).byteLength);return a[--b]};oc("/dev","random",c);oc("/dev","urandom",c);Yb("/dev/shm");Yb("/dev/shm/tmp")})();
(function(){Yb("/proc");var a=Yb("/proc/self");Yb("/proc/self/fd");Wb({ve(){var b=rb(a,"fd",16895,73);b.ke={lookup(c,d){var e=Tb(+d);c={parent:null,ve:{Lf:"fake"},ke:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=mc;h.FS_createDataFile=zb;h.FS_createPreloadedFile=Ab;h.FS_unlink=cc;h.FS_createLazyFile=qc;h.FS_createDevice=oc;
h.requestFullscreen=function(a,b){function c(){rd=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=zd,xd&&d.requestPointerLock(),rd=!0,yd?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=w[SDL.screen>>2]|8388608),Dd(h.canvas),Cd()):Dd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),yd?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=
w[SDL.screen>>2]&-8388609),Dd(h.canvas),Cd()):Dd(d));h.onFullScreen?.(rd);h.onFullscreen?.(rd)}xd=a;yd=b;"undefined"==typeof xd&&(xd=!0);"undefined"==typeof yd&&(yd=!1);var d=h.canvas;wd||(wd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=dd;h.setCanvasSize=function(a,b,c){Dd(h.canvas,a,b);c||Cd()};h.pauseMainLoop=function(){ad=null;kd++};h.resumeMainLoop=function(){kd++;var a=Xc,b=Yc,c=Zc;Zc=null;pd(c,0,!1,jd,!0);fd(a,b);ad()};
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.Fe&&a==h.canvas)return h.Fe;var e;if(b){var f={antialias:!1,alpha:!1,Kf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof fe&&(e=be(a,f)))var l=Ud[e].Me}else l=a.getContext("2d");if(!l)return null;c&&(h.Fe=l,b&&ee(e),h.qg=b,td.forEach(n=>n()),xb());return l};for(var U,Df=0;32>Df;++Df)Ye.push(Array(Df));
var Ef=new Float32Array(288);for(Df=0;288>=Df;++Df)jf[Df]=Ef.subarray(0,Df);var Ff=new Int32Array(288);for(Df=0;288>=Df;++Df)kf[Df]=Ff.subarray(0,Df);
var If={$a:(a,b)=>G(a)(b),db:function(a,b,c,d,e){try{for(var f=0,g=b?q[b>>2]:0,l=b?q[b+4>>2]:0,n=c?q[c>>2]:0,p=c?q[c+4>>2]:0,r=d?q[d>>2]:0,t=d?q[d+4>>2]:0,A=0,x=0,v=0,u=0,H=0,O=0,aa=(b?q[b>>2]:0)|(c?q[c>>2]:0)|(d?q[d>>2]:0),Wa=(b?q[b+4>>2]:0)|(c?q[c+4>>2]:0)|(d?q[d+4>>2]:0),I=0;I<a;I++){var Z=1<<I%32;if(32>I?aa&Z:Wa&Z){var gd=Tb(I),Zb=5;if(gd.le.bf){var Ne=-1;e&&(Ne=1E3*((b?q[e>>2]:0)+(b?q[e+4>>2]:0)/1E6));Zb=gd.le.bf(gd,Ne)}Zb&1&&(32>I?g&Z:l&Z)&&(32>I?A|=Z:x|=Z,f++);Zb&4&&(32>I?n&Z:p&Z)&&(32>I?v|=
Z:u|=Z,f++);Zb&2&&(32>I?r&Z:t&Z)&&(32>I?H|=Z:O|=Z,f++)}}b&&(q[b>>2]=A,q[b+4>>2]=x);c&&(q[c>>2]=v,q[c+4>>2]=u);d&&(q[d>>2]=H,q[d+4>>2]=O);return f}catch(hd){if("undefined"==typeof N||"ErrnoError"!==hd.name)throw hd;return-hd.ne}},Ya:function(a,b,c){try{var d=zc(a),e=d.Pe.accept(d);b&&Dc(b,e.family,Hc(e.xe),e.Ce,c);return e.stream.fd}catch(f){if("undefined"==typeof N||"ErrnoError"!==f.name)throw f;return-f.ne}},Xa:function(a,b,c){try{var d=zc(a),e=Mc(b,c);d.Pe.bind(d,e.qe,e.port);return 0}catch(f){if("undefined"==
typeof N||"ErrnoError"!==f.name)throw f;return-f.ne}},xb:function(a){try{a=a?F(m,a):"";var b=M(a,{Qe:!0});if(null===b.node)throw new J(44);if(!L(b.node.mode))throw new J(54);var c=Pb(b.node,"x");if(c)throw new J(c);cb=b.path;return 0}catch(d){if("undefined"==typeof N||"ErrnoError"!==d.name)throw d;return-d.ne}},Wa:function(a,b,c){try{var d=zc(a),e=Mc(b,c);d.Pe.connect(d,e.qe,e.port);return 0}catch(f){if("undefined"==typeof N||"ErrnoError"!==f.name)throw f;return-f.ne}},yb:function(a,b,c){try{b=b?
F(m,b):"";b=rc(a,b);if(c&-8)return-28;var d=M(b,{Qe:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Pb(d,a)?-2:0}catch(e){if("undefined"==typeof N||"ErrnoError"!==e.name)throw e;return-e.ne}},b:function(a,b,c){tc=c;try{var d=Tb(a);switch(b){case 0:var e=Nc();if(0>e)break;for(;Eb[e];)e++;return Vb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Nc(),d.flags|=e,0;case 12:return e=Nc(),va[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==
typeof N||"ErrnoError"!==f.name)throw f;return-f.ne}},qb:function(a,b){try{var c=Tb(a);return sc(dc,c.path,b)}catch(d){if("undefined"==typeof N||"ErrnoError"!==d.name)throw d;return-d.ne}},lb:function(a,b){try{if(0===b)return-28;var c=cb,d=hb(c)+1;if(b<d)return-68;E(c,m,a,b);return d}catch(e){if("undefined"==typeof N||"ErrnoError"!==e.name)throw e;return-e.ne}},hb:function(a,b,c){try{var d=Tb(a);if(!d.Re){var e=M(d.path,{Qe:!0}).node;if(!e.ke.readdir)throw new J(54);var f=e.ke.readdir(e);d.Re=f}a=
0;for(var g=jc(d,0,1),l=Math.floor(g/280);l<d.Re.length&&a+280<=c;){var n=d.Re[l];if("."===n){var p=d.node.id;var r=4}else if(".."===n)p=M(d.path,{parent:!0}).node.id,r=4;else{var t=tb(d.node,n);p=t.id;r=8192===(t.mode&61440)?2:L(t.mode)?4:40960===(t.mode&61440)?10:8}C=[p>>>0,(B=p,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];q[b+a>>2]=C[0];q[b+a+4>>2]=C[1];C=[280*(l+1)>>>0,(B=280*(l+1),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-
+(~~B>>>0))/4294967296)>>>0:0)];q[b+a+8>>2]=C[0];q[b+a+12>>2]=C[1];va[b+a+16>>1]=280;k[b+a+18]=r;E(n,m,b+a+19,256);a+=280;l+=1}jc(d,280*l,0);return a}catch(A){if("undefined"==typeof N||"ErrnoError"!==A.name)throw A;return-A.ne}},Va:function(a,b,c){try{var d=zc(a);if(!d.xe)return-53;Dc(b,d.family,Hc(d.xe),d.Ce,c);return 0}catch(e){if("undefined"==typeof N||"ErrnoError"!==e.name)throw e;return-e.ne}},Ua:function(a,b,c,d,e){try{var f=zc(a);return 1===b&&4===c?(q[d>>2]=f.error,q[e>>2]=4,f.error=null,
0):-50}catch(g){if("undefined"==typeof N||"ErrnoError"!==g.name)throw g;return-g.ne}},j:function(a,b,c){tc=c;try{var d=Tb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Le.hg){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Nc();q[e>>2]=25856;q[e+4>>2]=5;q[e+8>>2]=191;q[e+12>>2]=35387;for(var f=0;32>f;f++)k[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;
if(d.tty.Le.ig)for(e=Nc(),a=[],f=0;32>f;f++)a.push(k[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=Nc();return q[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=Nc();if(!d.le.$e)throw new J(59);return d.le.$e(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Le.jg&&(f=[24,80],e=Nc(),va[e>>1]=f[0],va[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof N||"ErrnoError"!==g.name)throw g;return-g.ne}},Sa:function(a,b){try{var c=
zc(a);c.Pe.listen(c,b);return 0}catch(d){if("undefined"==typeof N||"ErrnoError"!==d.name)throw d;return-d.ne}},mb:function(a,b){try{return a=a?F(m,a):"",sc(ec,a,b)}catch(c){if("undefined"==typeof N||"ErrnoError"!==c.name)throw c;return-c.ne}},kb:function(a,b,c){try{return b=b?F(m,b):"",b=rc(a,b),b=Ya(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),Yb(b,c),0}catch(d){if("undefined"==typeof N||"ErrnoError"!==d.name)throw d;return-d.ne}},ob:function(a,b,c,d){try{b=b?F(m,b):"";var e=d&256;b=rc(a,b,
d&4096);return sc(e?ec:dc,b,c)}catch(f){if("undefined"==typeof N||"ErrnoError"!==f.name)throw f;return-f.ne}},M:function(a,b,c,d){tc=d;try{b=b?F(m,b):"";b=rc(a,b);var e=d?Nc():0;return gc(b,c,e).fd}catch(f){if("undefined"==typeof N||"ErrnoError"!==f.name)throw f;return-f.ne}},ib:function(a){try{if(0==a)throw new J(21);var b={re:[],Tf:2};b.re.push({buffer:new Uint8Array(P.Ae),offset:0,Ee:0});var c=P.He(),d=P.He(),e=rb(P.root,c,4096,0),f=rb(P.root,d,4096,0);e.pipe=b;f.pipe=b;var g=Ub({path:c,node:e,
flags:0,seekable:!1,le:P.le});e.stream=g;var l=Ub({path:d,node:f,flags:1,seekable:!1,le:P.le});f.stream=l;var n=g.fd;var p=l.fd;q[a>>2]=n;q[a+4>>2]=p;return 0}catch(r){if("undefined"==typeof N||"ErrnoError"!==r.name)throw r;return-r.ne}},Ra:function(a,b,c,d,e,f){try{var g=zc(a),l=uc(g,c);if(!l)return 0;e&&Dc(e,g.family,Hc(l.qe),l.port,f);m.set(l.buffer,b);return l.buffer.byteLength}catch(n){if("undefined"==typeof N||"ErrnoError"!==n.name)throw n;return-n.ne}},eb:function(a,b,c,d){try{b=b?F(m,b):"";
d=d?F(m,d):"";b=rc(a,b);d=rc(c,d);a=b;var e=Za(a),f=Za(d),g=$a(a),l=$a(d);var n=M(a,{parent:!0});var p=n.node;n=M(d,{parent:!0});var r=n.node;if(!p||!r)throw new J(44);if(p.ve!==r.ve)throw new J(75);var t=tb(p,g),A=eb(a,f);if("."!==A.charAt(0))throw new J(28);A=eb(d,e);if("."!==A.charAt(0))throw new J(55);try{var x=tb(r,l)}catch(H){}if(t!==x){var v=L(t.mode),u=Sb(p,g,v);if(u)throw new J(u);if(u=x?Sb(r,l,v):Rb(r,l))throw new J(u);if(!p.ke.rename)throw new J(63);if(t.Oe||x&&x.Oe)throw new J(10);if(r!==
p&&(u=Pb(p,"w")))throw new J(u);Ob(t);try{p.ke.rename(t,r,l),t.parent=r}catch(H){throw H;}finally{Nb(t)}}return 0}catch(H){if("undefined"==typeof N||"ErrnoError"!==H.name)throw H;return-H.ne}},fb:function(a){try{return a=a?F(m,a):"",bc(a),0}catch(b){if("undefined"==typeof N||"ErrnoError"!==b.name)throw b;return-b.ne}},Qa:function(a,b,c,d,e,f){try{var g=zc(a),l=Mc(e,f,!0);return l?vc(g,k,b,c,l.qe,l.port):kc(g.stream,k,b,c)}catch(n){if("undefined"==typeof N||"ErrnoError"!==n.name)throw n;return-n.ne}},
L:function(a,b,c){try{return yc.createSocket(a,b,c).stream.fd}catch(d){if("undefined"==typeof N||"ErrnoError"!==d.name)throw d;return-d.ne}},pb:function(a,b){try{return a=a?F(m,a):"",sc(dc,a,b)}catch(c){if("undefined"==typeof N||"ErrnoError"!==c.name)throw c;return-c.ne}},gb:function(a,b,c){try{return b=b?F(m,b):"",b=rc(a,b),0===c?cc(b):512===c?bc(b):Ha("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof N||"ErrnoError"!==d.name)throw d;return-d.ne}},zb:()=>{Ha("")},tb:()=>1,vb:(a,
b,c)=>m.copyWithin(a,b,b+c),ab:()=>{Ta=!1;Sc=0},Oa:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));q[c>>2]=a.getSeconds();q[c+4>>2]=a.getMinutes();q[c+8>>2]=a.getHours();q[c+12>>2]=a.getDate();q[c+16>>2]=a.getMonth();q[c+20>>2]=a.getFullYear()-1900;q[c+24>>2]=a.getDay();b=a.getFullYear();q[c+28>>2]=(0!==b%4||0===b%100&&0!==b%400?Pc:Oc)[a.getMonth()]+a.getDate()-1|0;q[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=
(new Date(a.getFullYear(),0,1)).getTimezoneOffset();q[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},bb:(a,b)=>{Qc[a]&&(clearTimeout(Qc[a].id),delete Qc[a]);if(!b)return 0;var c=setTimeout(()=>{delete Qc[a];Vc(()=>Gf(a,Wc()))},b);Qc[a]={id:c,Qg:b};return 0},jb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset();w[a>>2]=60*Math.max(e,l);q[b>>2]=Number(e!=l);a=n=>n.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];
f=a(f);g=a(g);l<e?(E(f,m,c,17),E(g,m,d,17)):(E(f,m,d,17),E(g,m,c,17))},sc:a=>{if(12448==a)return Q=12288,1;Q=12300;return 0},hd:(a,b,c,d,e)=>{if(62E3!=a)Q=12296,c=0;else{if(b)for(;;){a=q[b>>2];if(12321==a)R.alpha=0<q[b+4>>2];else if(12325==a)R.depth=0<q[b+4>>2];else if(12326==a)R.stencil=0<q[b+4>>2];else if(12337==a)a=q[b+4>>2],R.antialias=0<a;else if(12338==a)a=q[b+4>>2],R.antialias=1==a;else if(12544==a)R.Ig=12547!=q[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(q[e>>2]=1),c&&0<d&&(w[c>>2]=62002),
Q=12288,c=1):(Q=12300,c=0)}return c},Na:(a,b,c,d)=>{if(62E3!=a)return Q=12296,0;for(a=1;;){b=q[d>>2];if(12440==b)a=q[d+4>>2];else if(12344==b)break;else return Q=12292,0;d+=8}if(2!=a)return Q=12293,0;R.Kf=a-1;R.Jg=0;Jd=be(h.canvas,R);if(0!=Jd)return Q=12288,ee(Jd),h.qg=!0,td.forEach(function(e){e()}),ee(null),62004;Q=12297;return 0},cb:(a,b)=>{if(62E3!=a)return Q=12296,0;if(62002!=b)return Q=12293,0;Q=12288;return 62006},Ta:(a,b)=>{if(62E3!=a)return Q=12296,0;if(62004!=b)return Q=12294,0;a=Jd;de===
Ud[a]&&(de=null);if("object"==typeof ve)for(var c=Ud[a].Me.canvas,d=0;d<qe.length;++d)qe[d].target!=c||re(d--);Ud[a]&&Ud[a].Me.canvas&&(Ud[a].Me.canvas.Ze=void 0);Ud[a]=null;Q=12288;Fd==b&&(Fd=0);return 1},nb:(a,b)=>{if(62E3!=a)return Q=12296,0;if(62006!=b)return Q=12301,1;Gd==b&&(Gd=0);Hd==b&&(Hd=0);Q=12288;return 1},sd:(a,b,c,d)=>{if(62E3!=a)return Q=12296,0;if(62002!=b)return Q=12293,0;if(!d)return Q=12300,0;Q=12288;switch(c){case 12320:return q[d>>2]=R.alpha?32:24,1;case 12321:return q[d>>2]=
R.alpha?8:0,1;case 12322:return q[d>>2]=8,1;case 12323:return q[d>>2]=8,1;case 12324:return q[d>>2]=8,1;case 12325:return q[d>>2]=R.depth?24:0,1;case 12326:return q[d>>2]=R.stencil?8:0,1;case 12327:return q[d>>2]=12344,1;case 12328:return q[d>>2]=62002,1;case 12329:return q[d>>2]=0,1;case 12330:return q[d>>2]=4096,1;case 12331:return q[d>>2]=16777216,1;case 12332:return q[d>>2]=4096,1;case 12333:return q[d>>2]=0,1;case 12334:return q[d>>2]=0,1;case 12335:return q[d>>2]=12344,1;case 12337:return q[d>>
2]=R.antialias?4:0,1;case 12338:return q[d>>2]=R.antialias?1:0,1;case 12339:return q[d>>2]=4,1;case 12340:return q[d>>2]=12344,1;case 12341:case 12342:case 12343:return q[d>>2]=-1,1;case 12345:case 12346:return q[d>>2]=0,1;case 12347:return q[d>>2]=0,1;case 12348:return q[d>>2]=1;case 12349:case 12350:return q[d>>2]=0,1;case 12351:return q[d>>2]=12430,1;case 12352:return q[d>>2]=4,1;case 12354:return q[d>>2]=0,1;default:return Q=12292,0}},O:a=>{Q=12288;return 0!=a&&1!=a?0:62E3},Ma:()=>Q,Nc:(a,b,c)=>
{if(62E3!=a)return Q=12296,0;b&&(q[b>>2]=1);c&&(q[c>>2]=4);Ed=!0;Q=12288;return 1},wb:(a,b,c,d)=>{if(62E3!=a)return Q=12296,0;if(0!=d&&62004!=d)return Q=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return Q=12301,0;ee(d?Jd:null);Fd=d;Hd=b;Gd=c;Q=12288;return 1},La:(a,b)=>{if(62E3!=a)return Q=12296,0;Q=12288;if(Id[b])return Id[b];switch(b){case 12371:a=ge("Emscripten");break;case 12372:a=ge("1.4 Emscripten EGL");break;case 12373:a=ge("");break;case 12429:a=ge("OpenGL_ES");break;default:return Q=12300,
0}return Id[b]=a},Cb:()=>{if(Ed)if(h.Fe)if(h.Fe.isContextLost())Q=12302;else return Q=12288,1;else Q=12290;else Q=12289;return 0},Nb:(a,b)=>{if(62E3!=a)return Q=12296,0;0==b?fd(0,0):fd(1,b);Q=12288;return 1},Yc:a=>{if(62E3!=a)return Q=12296,0;Hd=Gd=Fd=0;Ed=!1;Q=12288;return 1},hc:()=>{Q=12288;return 1},Yb:()=>{Q=12288;return 1},Ha:(a,b,c)=>{b=ie(b,c);return Ra[a](...b)},a:(a,b,c)=>{b=ie(b,c);return Ra[a](...b)},Ka:(a,b,c)=>{b=ie(b,c);return Ra[a](...b)},ub:()=>Date.now(),Ea:()=>{if(!ue())return-1;
me(Ve);var a=Je[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ia:()=>{me(We);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},e:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,c:(a,b,c)=>{a=W(a);if(!a)return-4;a=Ue(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},o:(a,b)=>{if(0>a||a>=we.length)return-5;if(!we[a])return-7;Xe(b,we[a]);return 0},
_a:()=>m.length,g:Wc,ta:()=>we.length,Ja:(a,b)=>{q[a>>2]=screen.width;q[b>>2]=screen.height},ja:a=>U.activeTexture(a),ia:(a,b)=>{U.attachShader(S[a],T[b])},Aa:(a,b)=>{U.Ke.beginQueryEXT(a,Vd[b])},ha:(a,b,c)=>{U.bindAttribLocation(S[a],b,c?F(m,c):"")},ga:(a,b)=>{U.bindBuffer(a,Pd[b])},fa:(a,b)=>{U.bindFramebuffer(a,Qd[b])},ea:(a,b)=>{U.bindRenderbuffer(a,Rd[b])},da:(a,b)=>{U.bindTexture(a,Sd[b])},ra:a=>{U.bindVertexArray(Td[a])},ca:(a,b,c,d)=>U.blendColor(a,b,c,d),ba:a=>U.blendEquation(a),aa:(a,b)=>
U.blendEquationSeparate(a,b),$:(a,b)=>U.blendFunc(a,b),_:(a,b,c,d)=>U.blendFuncSeparate(a,b,c,d),Z:(a,b,c,d)=>{U.bufferData(a,c?m.subarray(c,c+b):b,d)},Y:(a,b,c,d)=>{U.bufferSubData(a,b,m.subarray(d,d+c))},X:a=>U.checkFramebufferStatus(a),W:a=>U.clear(a),V:(a,b,c,d)=>U.clearColor(a,b,c,d),U:a=>U.clearDepth(a),T:a=>U.clearStencil(a),S:(a,b,c,d)=>{U.colorMask(!!a,!!b,!!c,!!d)},R:a=>{U.compileShader(T[a])},Wd:(a,b,c,d,e,f,g,l)=>{U.compressedTexImage2D(a,b,c,d,e,f,l?m.subarray(l,l+g):null)},Vd:(a,b,c,
d,e,f,g,l,n)=>{U.compressedTexSubImage2D(a,b,c,d,e,f,g,n?m.subarray(n,n+l):null)},Ud:(a,b,c,d,e,f,g,l)=>U.copyTexImage2D(a,b,c,d,e,f,g,l),Td:(a,b,c,d,e,f,g,l)=>U.copyTexSubImage2D(a,b,c,d,e,f,g,l),Sd:()=>{var a=Zd(S),b=U.createProgram();b.name=a;b.kf=b.hf=b.jf=0;b.zf=1;S[a]=b;return a},Rd:a=>{var b=Zd(T);T[b]=U.createShader(a);return b},Qd:a=>U.cullFace(a),Pd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=Pd[d];e&&(U.deleteBuffer(e),e.name=0,Pd[d]=null)}},Od:(a,b)=>{for(var c=0;c<a;++c){var d=q[b+
4*c>>2],e=Qd[d];e&&(U.deleteFramebuffer(e),e.name=0,Qd[d]=null)}},Nd:a=>{if(a){var b=S[a];b?(U.deleteProgram(b),b.name=0,S[a]=null):V||=1281}},Ca:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=Vd[d];e&&(U.Ke.deleteQueryEXT(e),Vd[d]=null)}},Md:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=Rd[d];e&&(U.deleteRenderbuffer(e),e.name=0,Rd[d]=null)}},Ld:a=>{if(a){var b=T[a];b?(U.deleteShader(b),T[a]=null):V||=1281}},Kd:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=Sd[d];e&&(U.deleteTexture(e),e.name=
0,Sd[d]=null)}},qa:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2];U.deleteVertexArray(Td[d]);Td[d]=null}},Jd:a=>U.depthFunc(a),Id:a=>{U.depthMask(!!a)},Hd:(a,b)=>U.depthRange(a,b),Gd:(a,b)=>{U.detachShader(S[a],T[b])},Fd:a=>U.disable(a),Ed:a=>{U.disableVertexAttribArray(a)},Dd:(a,b,c)=>{U.drawArrays(a,b,c)},ma:(a,b,c,d)=>{U.drawArraysInstanced(a,b,c,d)},na:(a,b)=>{for(var c=Ye[a],d=0;d<a;d++)c[d]=q[b+4*d>>2];U.drawBuffers(c)},Cd:(a,b,c,d)=>{U.drawElements(a,b,c,d)},la:(a,b,c,d,e)=>{U.drawElementsInstanced(a,
b,c,d,e)},Bd:a=>U.enable(a),Ad:a=>{U.enableVertexAttribArray(a)},za:a=>{U.Ke.endQueryEXT(a)},zd:()=>U.finish(),yd:()=>U.flush(),xd:(a,b,c,d)=>{U.framebufferRenderbuffer(a,b,c,Rd[d])},wd:(a,b,c,d,e)=>{U.framebufferTexture2D(a,b,c,Sd[d],e)},vd:a=>U.frontFace(a),ud:(a,b)=>{$d(a,b,"createBuffer",Pd)},rd:(a,b)=>{$d(a,b,"createFramebuffer",Qd)},Da:(a,b)=>{for(var c=0;c<a;c++){var d=U.Ke.createQueryEXT();if(!d){for(V||=1282;c<a;)q[b+4*c++>>2]=0;break}var e=Zd(Vd);d.name=e;Vd[e]=d;q[b+4*c>>2]=e}},qd:(a,b)=>
{$d(a,b,"createRenderbuffer",Rd)},pd:(a,b)=>{$d(a,b,"createTexture",Sd)},pa:(a,b)=>{$d(a,b,"createVertexArray",Td)},td:a=>U.generateMipmap(a),od:(a,b,c,d,e,f,g)=>{Ze("getActiveAttrib",a,b,c,d,e,f,g)},nd:(a,b,c,d,e,f,g)=>{Ze("getActiveUniform",a,b,c,d,e,f,g)},md:(a,b,c,d)=>{a=U.getAttachedShaders(S[a]);var e=a.length;e>b&&(e=b);q[c>>2]=e;for(b=0;b<e;++b)q[d+4*b>>2]=T.indexOf(a[b])},ld:(a,b)=>U.getAttribLocation(S[a],b?F(m,b):""),kd:(a,b)=>$e(a,b,4),jd:(a,b,c)=>{c?q[c>>2]=U.getBufferParameter(a,b):
V||=1281},id:()=>{var a=U.getError()||V;V=0;return a},gd:(a,b)=>$e(a,b,2),fd:(a,b,c,d)=>{a=U.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;q[d>>2]=a},ed:(a,b)=>$e(a,b,0),cd:(a,b,c,d)=>{a=U.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,m,d,b):0;c&&(q[c>>2]=b)},dd:(a,b,c)=>{if(c)if(a>=Od)V||=1281;else if(a=S[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(35719==
b){if(!a.kf)for(b=0;b<U.getProgramParameter(a,35718);++b)a.kf=Math.max(a.kf,U.getActiveUniform(a,b).name.length+1);q[c>>2]=a.kf}else if(35722==b){if(!a.hf)for(b=0;b<U.getProgramParameter(a,35721);++b)a.hf=Math.max(a.hf,U.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.hf}else if(35381==b){if(!a.jf)for(b=0;b<U.getProgramParameter(a,35382);++b)a.jf=Math.max(a.jf,U.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.jf}else q[c>>2]=U.getProgramParameter(a,b);else V||=1281},ua:af,wa:bf,sa:af,va:bf,xa:(a,
b,c)=>{c?q[c>>2]=U.Ke.getQueryEXT(a,b):V||=1281},bd:(a,b,c)=>{c?q[c>>2]=U.getRenderbufferParameter(a,b):V||=1281},$c:(a,b,c,d)=>{a=U.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,m,d,b):0;c&&(q[c>>2]=b)},_c:(a,b,c,d)=>{a=U.getShaderPrecisionFormat(a,b);q[c>>2]=a.rangeMin;q[c+4>>2]=a.rangeMax;q[d>>2]=a.precision},Zc:(a,b,c,d)=>{if(a=U.getShaderSource(T[a]))b=0<b&&d?E(a,m,d,b):0,c&&(q[c>>2]=b)},ad:(a,b,c)=>{c?35716==b?(a=U.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),
q[c>>2]=a?a.length+1:0):35720==b?(a=U.getShaderSource(T[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=U.getShaderParameter(T[a],b):V||=1281},Xc:a=>{var b=Wd[a];if(!b){switch(a){case 7939:b=ge(cf().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||(V||=1280);b=b?ge(b):0;break;case 7938:b=ge(`OpenGL ES 2.0 (${U.getParameter(7938)})`);break;case 35724:b=U.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);
b=ge(b);break;default:V||=1280}Wd[a]=b}return b},Wc:(a,b,c)=>{c?y[c>>2]=U.getTexParameter(a,b):V||=1281},Vc:(a,b,c)=>{c?q[c>>2]=U.getTexParameter(a,b):V||=1281},Sc:(a,b)=>{b=b?F(m,b):"";if(a=S[a]){ef(a);var c=a.df,d=0,e=b,f=df(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Vf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else V||=1281;return-1},Uc:(a,b,c)=>{ff(a,b,c,2)},Tc:(a,b,c)=>{ff(a,b,c,0)},Pc:(a,b,c)=>{c?q[c>>2]=U.getVertexAttribOffset(a,b):V||=1281},Rc:(a,
b,c)=>{gf(a,b,c,2)},Qc:(a,b,c)=>{gf(a,b,c,5)},Oc:(a,b)=>U.hint(a,b),Mc:a=>(a=Pd[a])?U.isBuffer(a):0,Lc:a=>U.isEnabled(a),Kc:a=>(a=Qd[a])?U.isFramebuffer(a):0,Jc:a=>(a=S[a])?U.isProgram(a):0,Ba:a=>(a=Vd[a])?U.Ke.isQueryEXT(a):0,Ic:a=>(a=Rd[a])?U.isRenderbuffer(a):0,Hc:a=>(a=T[a])?U.isShader(a):0,Gc:a=>(a=Sd[a])?U.isTexture(a):0,oa:a=>(a=Td[a])?U.isVertexArray(a):0,Fc:a=>U.lineWidth(a),Ec:a=>{a=S[a];U.linkProgram(a);a.df=0;a.Vf={}},Dc:(a,b)=>{3317==a?Xd=b:3314==a&&(Yd=b);U.pixelStorei(a,b)},Cc:(a,b)=>
U.polygonOffset(a,b),ya:(a,b)=>{U.Ke.queryCounterEXT(Vd[a],b)},Bc:(a,b,c,d,e,f,g)=>{(g=hf(f,e,c,d,g))?U.readPixels(a,b,c,d,e,f,g):V||=1280},Ac:()=>{},zc:(a,b,c,d)=>U.renderbufferStorage(a,b,c,d),yc:(a,b)=>{U.sampleCoverage(a,!!b)},xc:(a,b,c,d)=>U.scissor(a,b,c,d),wc:()=>{V||=1280},vc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=w[c+4*f>>2])?F(m,g,d?w[d+4*f>>2]:void 0):"";e+=g}U.shaderSource(T[a],e)},uc:(a,b,c)=>U.stencilFunc(a,b,c),tc:(a,b,c,d)=>U.stencilFuncSeparate(a,b,c,d),rc:a=>U.stencilMask(a),
qc:(a,b)=>U.stencilMaskSeparate(a,b),pc:(a,b,c)=>U.stencilOp(a,b,c),oc:(a,b,c,d)=>U.stencilOpSeparate(a,b,c,d),nc:(a,b,c,d,e,f,g,l,n)=>{n=n?hf(l,g,d,e,n):null;U.texImage2D(a,b,c,d,e,f,g,l,n)},mc:(a,b,c)=>U.texParameterf(a,b,c),lc:(a,b,c)=>{U.texParameterf(a,b,y[c>>2])},kc:(a,b,c)=>U.texParameteri(a,b,c),jc:(a,b,c)=>{U.texParameteri(a,b,q[c>>2])},ic:(a,b,c,d,e,f,g,l,n)=>{n=n?hf(l,g,e,f,n):null;U.texSubImage2D(a,b,c,d,e,f,g,l,n)},gc:(a,b)=>{U.uniform1f(X(a),b)},fc:(a,b,c)=>{if(288>=b)for(var d=jf[b],
e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);U.uniform1fv(X(a),d)},ec:(a,b)=>{U.uniform1i(X(a),b)},dc:(a,b,c)=>{if(288>=b)for(var d=kf[b],e=0;e<b;++e)d[e]=q[c+4*e>>2];else d=q.subarray(c>>2,c+4*b>>2);U.uniform1iv(X(a),d)},cc:(a,b,c)=>{U.uniform2f(X(a),b,c)},bc:(a,b,c)=>{if(144>=b)for(var d=jf[2*b],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);U.uniform2fv(X(a),d)},ac:(a,b,c)=>{U.uniform2i(X(a),b,c)},$b:(a,b,c)=>{if(144>=b)for(var d=kf[2*b],
e=0;e<2*b;e+=2)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2];else d=q.subarray(c>>2,c+8*b>>2);U.uniform2iv(X(a),d)},_b:(a,b,c,d)=>{U.uniform3f(X(a),b,c,d)},Zb:(a,b,c)=>{if(96>=b)for(var d=jf[3*b],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);U.uniform3fv(X(a),d)},Xb:(a,b,c,d)=>{U.uniform3i(X(a),b,c,d)},Wb:(a,b,c)=>{if(96>=b)for(var d=kf[3*b],e=0;e<3*b;e+=3)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2];else d=q.subarray(c>>
2,c+12*b>>2);U.uniform3iv(X(a),d)},Vb:(a,b,c,d,e)=>{U.uniform4f(X(a),b,c,d,e)},Ub:(a,b,c)=>{if(72>=b){var d=jf[4*b],e=y;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=y.subarray(c>>2,c+16*b>>2);U.uniform4fv(X(a),d)},Tb:(a,b,c,d,e)=>{U.uniform4i(X(a),b,c,d,e)},Sb:(a,b,c)=>{if(72>=b)for(var d=kf[4*b],e=0;e<4*b;e+=4)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2],d[e+3]=q[c+(4*e+12)>>2];else d=q.subarray(c>>2,c+16*b>>2);U.uniform4iv(X(a),
d)},Rb:(a,b,c,d)=>{if(72>=b)for(var e=jf[4*b],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);U.uniformMatrix2fv(X(a),!!c,e)},Qb:(a,b,c,d)=>{if(32>=b)for(var e=jf[9*b],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,
d+36*b>>2);U.uniformMatrix3fv(X(a),!!c,e)},Pb:(a,b,c,d)=>{if(18>=b){var e=jf[16*b],f=y;d>>=2;for(var g=0;g<16*b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=y.subarray(d>>2,d+64*b>>2);U.uniformMatrix4fv(X(a),!!c,e)},Ob:a=>{a=S[a];U.useProgram(a);U.Yf=a},Mb:a=>{U.validateProgram(S[a])},Lb:(a,
b)=>U.vertexAttrib1f(a,b),Kb:(a,b)=>{U.vertexAttrib1f(a,y[b>>2])},Jb:(a,b,c)=>U.vertexAttrib2f(a,b,c),Ib:(a,b)=>{U.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},Hb:(a,b,c,d)=>U.vertexAttrib3f(a,b,c,d),Gb:(a,b)=>{U.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},Fb:(a,b,c,d,e)=>U.vertexAttrib4f(a,b,c,d,e),Eb:(a,b)=>{U.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},ka:(a,b)=>{U.vertexAttribDivisor(a,b)},Db:(a,b,c,d,e,f)=>{U.vertexAttribPointer(a,b,c,!!d,e,f)},Bb:(a,b,c,d)=>U.viewport(a,b,c,d),m:()=>
0,Fa:(a,b,c)=>lf(a,{xf:q[c>>2],qf:q[c+4>>2],dg:q[c+8>>2],bg:b,ff:q[c+12>>2],Cf:q[c+16>>2]}),K:(a,b)=>{a=W(a);return a?a.requestPointerLock?ne()?We(a):b?(le(We,2,[a]),1):-2:-1:-4},Za:()=>{Ha("OOM")},p:mf,q:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:nf(a,b),C:(a,b,c,d)=>of(a,b,c,d,12,"blur"),d:Qe,h:(a,b,c)=>{a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},D:(a,b,c,d)=>of(a,b,c,d,13,"focus"),t:(a,b,c,d)=>{if(!ue())return-1;a=W(a);if(!a)return-4;pf(a,b,c,d,"webkitfullscreenchange");
return pf(a,b,c,d,"fullscreenchange")},n:(a,b,c)=>mf()?-1:qf(a,b,c,26,"gamepadconnected"),P:(a,b,c)=>mf()?-1:qf(a,b,c,27,"gamepaddisconnected"),w:(a,b,c,d)=>rf(a,b,c,d,2,"keydown"),u:(a,b,c,d)=>rf(a,b,c,d,1,"keypress"),v:(a,b,c,d)=>rf(a,b,c,d,3,"keyup"),Xd:(a,b,c)=>{a=G(a);pd(a,b,c)},I:(a,b,c,d)=>tf(a,b,c,d,5,"mousedown"),G:(a,b,c,d)=>tf(a,b,c,d,33,"mouseenter"),F:(a,b,c,d)=>tf(a,b,c,d,34,"mouseleave"),J:(a,b,c,d)=>tf(a,b,c,d,8,"mousemove"),H:(a,b,c,d)=>tf(a,b,c,d,6,"mouseup"),x:(a,b,c,d)=>{if(!document||
!document.body||!(document.body.requestPointerLock||document.body.pe||document.body.af||document.body.Se))return-1;a=W(a);if(!a)return-4;uf(a,b,c,d,"mozpointerlockchange");uf(a,b,c,d,"webkitpointerlockchange");uf(a,b,c,d,"mspointerlockchange");return uf(a,b,c,d,"pointerlockchange")},s:(a,b,c,d)=>vf(a,b,c,d),y:(a,b,c,d)=>wf(a,b,c,d,25,"touchcancel"),A:(a,b,c,d)=>wf(a,b,c,d,23,"touchend"),z:(a,b,c,d)=>wf(a,b,c,d,24,"touchmove"),B:(a,b,c,d)=>wf(a,b,c,d,22,"touchstart"),r:(a,b,c)=>Je[1]?xf(a,b,c):-4,
E:(a,b,c,d)=>(a=W(a))?"undefined"!=typeof a.onwheel?yf(a,b,c,d):-1:-4,Ga:a=>document.title=a?F(m,a):"",l:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},rb:(a,b)=>{var c=0;Bf().forEach((d,e)=>{var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)k[e++]=d.charCodeAt(f);k[e]=0;c+=d.length+1});return 0},sb:(a,b)=>{var c=Bf();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0},k:Uc,f:function(a){try{var b=Tb(a);
ic(b);return 0}catch(c){if("undefined"==typeof N||"ErrnoError"!==c.name)throw c;return c.ne}},N:function(a,b,c,d){try{a:{var e=Tb(a);a=b;for(var f,g=b=0;g<c;g++){var l=w[a>>2],n=w[a+4>>2];a+=8;var p=e,r=f,t=k;if(0>n||0>r)throw new J(28);if(null===p.fd)throw new J(8);if(1===(p.flags&2097155))throw new J(8);if(L(p.node.mode))throw new J(31);if(!p.le.read)throw new J(28);var A="undefined"!=typeof r;if(!A)r=p.position;else if(!p.seekable)throw new J(70);var x=p.le.read(p,t,l,n,r);A||(p.position+=x);var v=
x;if(0>v){var u=-1;break a}b+=v;if(v<n)break;"undefined"!=typeof f&&(f+=v)}u=b}w[d>>2]=u;return 0}catch(H){if("undefined"==typeof N||"ErrnoError"!==H.name)throw H;return H.ne}},Pa:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Tb(a);jc(f,b,d);C=[f.position>>>0,(B=f.position,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];q[e>>2]=C[0];q[e+4>>2]=C[1];f.Re&&0===b&&0===d&&(f.Re=null);return 0}catch(g){if("undefined"==
typeof N||"ErrnoError"!==g.name)throw g;return g.ne}},i:function(a,b,c,d){try{a:{var e=Tb(a);a=b;for(var f,g=b=0;g<c;g++){var l=w[a>>2],n=w[a+4>>2];a+=8;var p=kc(e,k,l,n,f);if(0>p){var r=-1;break a}b+=p;"undefined"!=typeof f&&(f+=p)}r=b}w[d>>2]=r;return 0}catch(t){if("undefined"==typeof N||"ErrnoError"!==t.name)throw t;return t.ne}},Q:(a,b,c,d)=>{function e(t,A,x,v,u,H){var O=10===t?28:16;u=10===t?Kc(u):Ic(u);O=D(O);!Dc(O,t,u,H)||Ha();u=D(32);q[u+4>>2]=t;q[u+8>>2]=A;q[u+12>>2]=x;w[u+24>>2]=v;w[u+
20>>2]=O;q[u+16>>2]=10===t?28:16;q[u+28>>2]=0;return u}var f=0,g=0,l=0,n=0,p=0,r=0;c&&(l=q[c>>2],n=q[c+4>>2],p=q[c+8>>2],r=q[c+12>>2]);p&&!r&&(r=2===p?17:6);!p&&r&&(p=17===r?2:1);0===r&&(r=6);0===p&&(p=1);if(!a&&!b)return-2;if(l&-1088||0!==c&&q[c>>2]&2&&!a)return-1;if(l&32)return-2;if(0!==p&&1!==p&&2!==p)return-7;if(0!==n&&2!==n&&10!==n)return-6;if(b&&(b=b?F(m,b):"",g=parseInt(b,10),isNaN(g)))return l&1024?-2:-8;if(!a)return 0===n&&(n=2),0===(l&1)&&(2===n?f=Hf(2130706433):f=[0,0,0,1]),a=e(n,p,r,null,
f,g),w[d>>2]=a,0;a=a?F(m,a):"";f=Ac(a);if(null!==f)if(0===n||2===n)n=2;else if(10===n&&l&8)f=[0,0,Hf(65535),f],n=10;else return-2;else if(f=Cc(a),null!==f)if(0===n||10===n)n=10;else return-2;if(null!=f)return a=e(n,p,r,a,f,g),w[d>>2]=a,0;if(l&4)return-2;a=Hc(a);f=Ac(a);0===n?n=2:10===n&&(f=[0,0,Hf(65535),f]);a=e(n,p,r,null,f,g);w[d>>2]=a;return 0},Ab:Tc},Y=function(){function a(c){Y=c.exports;sa=Y.Yd;c=sa.buffer;h.HEAP8=k=new Int8Array(c);h.HEAP16=va=new Int16Array(c);h.HEAPU8=m=new Uint8Array(c);
h.HEAPU16=wa=new Uint16Array(c);h.HEAP32=q=new Int32Array(c);h.HEAPU32=w=new Uint32Array(c);h.HEAPF32=y=new Float32Array(c);h.HEAPF64=z=new Float64Array(c);Va=Y.$d;ya.unshift(Y.Zd);Ga("wasm-instantiate");return Y}var b={a:If};Fa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return ea(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ja||=Ia("drom.wasm")?"drom.wasm":h.locateFile?h.locateFile("drom.wasm",ka):ka+"drom.wasm";Na(b,function(c){a(c.instance)});
return{}}(),Jf=h._main=(a,b)=>(Jf=h._main=Y._d)(a,b),Jc=a=>(Jc=Y.ae)(a),Bc=a=>(Bc=Y.be)(a),D=a=>(D=Y.ce)(a),Hf=a=>(Hf=Y.de)(a),Gf=(a,b)=>(Gf=Y.ee)(a,b),Oe=a=>(Oe=Y.fe)(a),Ke=a=>(Ke=Y.ge)(a),Me=()=>(Me=Y.he)();h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Y.ie)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Y.je)(a,b);h.addRunDependency=Fa;h.removeRunDependency=Ga;h.FS_createPreloadedFile=Ab;h.FS_unlink=a=>cc(a);h.FS_createPath=mc;h.FS_createDevice=oc;h.FS_createDataFile=(a,b,c,d,e,f)=>{zb(a,b,c,d,e,f)};
h.FS_createLazyFile=qc;var Kf;Ea=function Lf(){Kf||Mf();Kf||(Ea=Lf)};function Nf(a=[]){var b=Jf;a.unshift(ia);var c=a.length,d=Ke(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=Le(g);e+=4});w[e>>2]=0;try{var f=b(c,d);Uc(f,!0)}catch(g){Rc(g)}}
function Mf(){var a=ha;function b(){if(!Kf&&(Kf=!0,h.calledRun=!0,!ta)){h.noFSInit||lc||(lc=!0,h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?oc("/dev","stdin",h.stdin):ac("/dev/tty","/dev/stdin"),h.stdout?oc("/dev","stdout",null,h.stdout):ac("/dev/tty","/dev/stdout"),h.stderr?oc("/dev","stderr",null,h.stderr):ac("/dev/tty1","/dev/stderr"),gc("/dev/stdin",0),gc("/dev/stdout",1),gc("/dev/stderr",1));Hb=!1;yc.root=Wb(yc,null);P.root=Wb(P,null);Sa(ya);Sa(za);h.onRuntimeInitialized?.();Of&&
Nf(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Aa.unshift(c)}Sa(Aa)}}if(!(0<Ca)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();Sa(xa);0<Ca||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Of=!0;
h.noInitialRun&&(Of=!1);Mf();
